"""Tests for scripts/build.py (plan section 15.2 and the section 18 addendum).

Run from the repository root:
    py -3 -m unittest discover -s scripts/tests -v
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))
import build  # noqa: E402

GIT_ID = ["-c", "user.name=test", "-c", "user.email=test@example.com"]


def _rmtree(path):
    def onerr(func, p, exc):
        os.chmod(p, 0o700)
        func(p)
    shutil.rmtree(path, onerror=onerr)


def copy_repo(dest):
    """Copy the repository (without .git and caches) into dest."""
    shutil.copytree(
        REPO, dest, dirs_exist_ok=True,
        ignore=shutil.ignore_patterns(".git", "__pycache__", "tests"),
    )
    return Path(dest)


def errors_of(findings):
    return [f for f in findings if f.level == "ERROR"]


def has_error(findings, text, path=None):
    return any(
        text in f.message and (path is None or f.path == path)
        for f in errors_of(findings)
    )


def read(root, rel):
    return (Path(root) / rel).read_bytes().decode("utf-8")


class TempRepoCase(unittest.TestCase):
    """Each test gets a fresh copy of the repository in a temp folder."""

    def setUp(self):
        self._tmp = tempfile.mkdtemp(prefix="ga-test-")
        self.addCleanup(_rmtree, self._tmp)
        self.root = copy_repo(Path(self._tmp) / "repo")

    def edit_json(self, rel, fn):
        p = self.root / rel
        data = json.loads(p.read_text(encoding="utf-8"))
        fn(data)
        p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")

    def edit_text(self, rel, fn):
        p = self.root / rel
        text = p.read_bytes().decode("utf-8")
        p.write_bytes(fn(text).encode("utf-8"))


class OutputsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        catalog, findings = build.load_sources(REPO)
        assert catalog is not None, findings
        cls.outputs = build.render_outputs(catalog)
        cls.catalog = catalog

    def test_repo_validates_clean(self):
        self.assertEqual(errors_of(build.validate(REPO)), [])

    def test_generated_file_set(self):
        expected = {
            ".claude-plugin/marketplace.json",
            ".agents/plugins/marketplace.json",
            "dist/claude-code/dev-pipeline/.claude-plugin/plugin.json",
            "dist/claude-code/dev-pipeline/skills/pipeline/SKILL.md",
            "dist/codex/dev-pipeline/skills/pipeline/SKILL.md",
            "dist/codex-plugin/dev-pipeline/plugin.json",
            "dist/codex-plugin/dev-pipeline/skills/pipeline/SKILL.md",
        }
        for a in ("architect", "coder", "tester"):
            expected.add("dist/claude-code/dev-pipeline/agents/%s.md" % a)
            expected.add("dist/codex/dev-pipeline/agents/%s.toml" % a)
        self.assertEqual(set(self.outputs), expected)

    def test_architect_claude_matches_plan_8_3(self):
        text = self.outputs["dist/claude-code/dev-pipeline/agents/architect.md"]
        want = (
            "---\n"
            "name: architect\n"
            'description: "Designs the solution before any code is written and saves an '
            "implementation plan to docs/plan.md. Use proactively for new features, refactors, "
            'and architecture decisions. Never edits project code."\n'
            "tools: Read, Grep, Glob, Write, WebFetch, WebSearch\n"
            "model: opus\n"
            "effort: max\n"
            "color: blue\n"
            "---\n\n"
            "You are a senior software architect. You read the relevant code and turn a request "
            "into an implementation plan that a coder can execute without guessing. "
            "You never write project code.\n"
        )
        self.assertTrue(text.startswith(want), text[:600])
        self.assertTrue(read(REPO, "dist/claude-code/dev-pipeline/agents/architect.md").startswith(want))

    def test_architect_codex_matches_plan_8_3(self):
        want = (
            "# Generated by scripts/build.py from agents/architect/ in "
            "https://github.com/alejogaisser/gaisser-agents. Do not edit.\n"
            "# License: Apache-2.0. See the NOTICE file in the repository.\n"
            'name = "architect"\n'
            'description = "Designs the solution before any code is written and saves an '
            "implementation plan to docs/plan.md. Use proactively for new features, refactors, "
            'and architecture decisions. Never edits project code."\n'
            'model_reasoning_effort = "max"\n'
            'sandbox_mode = "workspace-write"\n'
            'developer_instructions = """\n'
            "You are a senior software architect. You read the relevant code and turn a request "
            "into an implementation plan that a coder can execute without guessing. "
            "You never write project code.\n"
        )
        self.assertTrue(self.outputs["dist/codex/dev-pipeline/agents/architect.toml"].startswith(want))
        self.assertTrue(read(REPO, "dist/codex/dev-pipeline/agents/architect.toml").startswith(want))

    def test_coder_and_tester_mappings(self):
        cases = {
            "coder": ("Read, Grep, Glob, Edit, Write, NotebookEdit, Bash, PowerShell, LSP",
                      "sonnet", "medium"),
            "tester": ("Read, Grep, Glob, Edit, Write, Bash, PowerShell", "sonnet", "medium"),
        }
        for name, (tools, model, effort) in cases.items():
            md = self.outputs["dist/claude-code/dev-pipeline/agents/%s.md" % name]
            self.assertIn("\ntools: %s\n" % tools, md)
            self.assertIn("\nmodel: %s\n" % model, md)
            self.assertIn("\neffort: %s\n" % effort, md)
            data = tomllib.loads(self.outputs["dist/codex/dev-pipeline/agents/%s.toml" % name])
            self.assertEqual(data["sandbox_mode"], "workspace-write")
            self.assertEqual(data["model_reasoning_effort"], effort)
            self.assertNotIn("model", data)

    def test_codex_toml_roundtrip_equals_prompt(self):
        for name in ("architect", "coder", "tester"):
            data = tomllib.loads(self.outputs["dist/codex/dev-pipeline/agents/%s.toml" % name])
            prompt = build.normalize_body((REPO / "agents" / name / "prompt.md").read_text(encoding="utf-8"))
            self.assertEqual(data["developer_instructions"], prompt)
            self.assertEqual(data["name"], name)

    def test_token_rendering_differs_per_tool(self):
        claude = self.outputs["dist/claude-code/dev-pipeline/skills/pipeline/SKILL.md"]
        codex = self.outputs["dist/codex/dev-pipeline/skills/pipeline/SKILL.md"]
        for a in ("architect", "coder", "tester"):
            self.assertIn("| `dev-pipeline:%s` |" % a, claude)
            self.assertIn("| `%s` |" % a, codex)
            self.assertNotIn("dev-pipeline:%s" % a, codex)
        self.assertNotIn("{{", claude)
        self.assertNotIn("{{", codex)

    def test_skill_frontmatter_fields(self):
        def fm_keys(text):
            lines = text.split("\n")
            self.assertEqual(lines[0], "---")
            end = lines.index("---", 1)
            return [ln.split(":", 1)[0] for ln in lines[1:end]]

        claude = self.outputs["dist/claude-code/dev-pipeline/skills/pipeline/SKILL.md"]
        codex = self.outputs["dist/codex/dev-pipeline/skills/pipeline/SKILL.md"]
        self.assertEqual(fm_keys(claude), ["name", "description", "argument-hint", "license"])
        self.assertEqual(fm_keys(codex), ["name", "description", "license"])

    def test_marketplace_and_plugin_json(self):
        mp = json.loads(self.outputs[".claude-plugin/marketplace.json"])
        self.assertEqual(mp["name"], "gaisser-agents")
        self.assertEqual(mp["plugins"][0]["source"], "./dist/claude-code/dev-pipeline")
        pj = json.loads(self.outputs["dist/claude-code/dev-pipeline/.claude-plugin/plugin.json"])
        self.assertEqual(pj["license"], "Apache-2.0")
        self.assertTrue(pj["homepage"].endswith("#dev-pipeline"))
        self.assertEqual(pj["repository"], "https://github.com/alejogaisser/gaisser-agents")

    def test_outputs_are_lf_and_end_with_newline(self):
        for path, content in self.outputs.items():
            self.assertNotIn("\r", content, path)
            self.assertTrue(content.endswith("\n"), path)
            self.assertFalse(content.endswith("\n\n"), path)


class CodexPluginTest(unittest.TestCase):
    """Section 18 addendum."""

    @classmethod
    def setUpClass(cls):
        catalog, _ = build.load_sources(REPO)
        cls.outputs = build.render_outputs(catalog)

    def test_plugin_outputs_generated_and_in_sync_on_disk(self):
        for rel in ("dist/codex-plugin/dev-pipeline/plugin.json",
                    "dist/codex-plugin/dev-pipeline/skills/pipeline/SKILL.md",
                    ".agents/plugins/marketplace.json"):
            self.assertTrue((REPO / rel).is_file(), rel)
            self.assertEqual(read(REPO, rel).replace("\r\n", "\n"), self.outputs[rel], rel)

    def test_codex_plugin_skill_equals_codex_skill(self):
        self.assertEqual(
            read(REPO, "dist/codex-plugin/dev-pipeline/skills/pipeline/SKILL.md"),
            read(REPO, "dist/codex/dev-pipeline/skills/pipeline/SKILL.md"),
        )

    def test_plugin_json_fields(self):
        pj = json.loads(read(REPO, "dist/codex-plugin/dev-pipeline/plugin.json"))
        self.assertEqual(pj["name"], "dev-pipeline")
        self.assertEqual(pj["version"], "1.0.0")
        self.assertEqual(pj["license"], "Apache-2.0")
        self.assertTrue(pj["homepage"].endswith("#dev-pipeline"))
        self.assertIn("author", pj)
        self.assertIn("description", pj)

    def test_codex_marketplace_source_path_exists_and_relative(self):
        mp = json.loads(read(REPO, ".agents/plugins/marketplace.json"))
        self.assertEqual(mp["name"], "gaisser-agents")
        entry = [p for p in mp["plugins"] if p["name"] == "dev-pipeline"]
        self.assertEqual(len(entry), 1)
        path = entry[0]["source"]["path"]
        self.assertTrue(path.startswith("./"), path)
        self.assertNotIn("..", path)
        self.assertNotIn("\\", path)
        target = REPO / path
        self.assertTrue(target.is_dir(), path)
        self.assertTrue((target / "plugin.json").is_file())
        self.assertTrue((target / "skills" / "pipeline" / "SKILL.md").is_file())

    def test_codex_plugin_carries_no_agents(self):
        self.assertFalse((REPO / "dist/codex-plugin/dev-pipeline/agents").exists())


class EscapingTest(unittest.TestCase):
    def test_triple_quotes_and_backslashes_roundtrip(self):
        body = 'path C:\\dir\\n and """triple""" and "" and \\"""\nline two\\\n'
        body = build.normalize_body(body)
        toml = 'developer_instructions = """\n' + build.toml_escape_ml(body) + '"""\n'
        self.assertEqual(tomllib.loads(toml)["developer_instructions"], body)

    def test_dq_roundtrip_in_toml(self):
        s = 'He said "hi" \\ and \\n'
        self.assertEqual(tomllib.loads("k = " + build.dq(s) + "\n")["k"], s)


class SourceValidationTest(TempRepoCase):
    def test_baseline_clean(self):
        self.assertEqual(errors_of(build.validate(self.root)), [])

    def agent_edit(self, name, fn):
        self.edit_json("agents/%s/agent.json" % name, fn)

    def test_unknown_key_in_agent_json(self):
        self.agent_edit("coder", lambda d: d.update(bogus=1))
        self.assertTrue(has_error(build.validate(self.root), "unknown key 'bogus'"))

    def test_unknown_capability(self):
        self.agent_edit("coder", lambda d: d["capabilities"].append("teleport"))
        self.assertTrue(has_error(build.validate(self.root), "capabilities"))

    def test_capabilities_without_read(self):
        self.agent_edit("coder", lambda d: d.update(capabilities=["edit", "shell"]))
        self.assertTrue(has_error(build.validate(self.root), "must include 'read'"))

    def test_fast_tier_with_effort(self):
        self.agent_edit("coder", lambda d: d.update(model="fast", effort="low"))
        self.assertTrue(has_error(build.validate(self.root), "must not set effort"))

    def test_deep_tier_without_effort(self):
        self.agent_edit("architect", lambda d: d.pop("effort"))
        self.assertTrue(has_error(build.validate(self.root), "effort is required"))

    def test_description_without_use(self):
        self.agent_edit("coder", lambda d: d.update(
            description="Implements a plan step by step following the project conventions closely."))
        self.assertTrue(has_error(build.validate(self.root), "'Use '"))

    def test_description_too_long(self):
        self.agent_edit("coder", lambda d: d.update(description="Use " + "x" * 420))
        self.assertTrue(has_error(build.validate(self.root), "expected 40 to 400"))

    def test_name_differs_from_folder(self):
        self.agent_edit("coder", lambda d: d.update(name="coder2"))
        self.assertTrue(has_error(build.validate(self.root), "must equal the folder name"))

    def test_reserved_name_worker(self):
        shutil.move(str(self.root / "agents/coder"), str(self.root / "agents/worker"))
        self.edit_json("agents/worker/agent.json", lambda d: d.update(name="worker"))
        self.edit_json("catalog.json",
                       lambda d: d["plugins"][0].update(agents=["architect", "worker", "tester"]))
        self.assertTrue(has_error(build.validate(self.root), "reserved Codex name"))

    def test_prompt_missing_boundaries_heading(self):
        self.edit_text("agents/tester/prompt.md", lambda t: t.replace("## Boundaries", "## Limits"))
        self.assertTrue(has_error(build.validate(self.root), "## Boundaries"))

    def test_prompt_missing_boundary_phrase(self):
        self.edit_text("agents/tester/prompt.md",
                       lambda t: t.replace("You cannot ask the user questions", "You may ask"))
        self.assertTrue(has_error(build.validate(self.root), "boundary phrase"))

    def test_prompt_with_webfetch(self):
        self.edit_text("agents/tester/prompt.md", lambda t: t.replace("Process", "Process WebFetch", 1))
        self.assertTrue(has_error(build.validate(self.root), "WebFetch"))

    def test_prompt_with_braces(self):
        self.edit_text("agents/tester/prompt.md", lambda t: t.rstrip("\n") + "\n{{x}}\n")
        self.assertTrue(has_error(build.validate(self.root), "{{"))

    def test_skill_description_too_long(self):
        self.edit_json("skills/pipeline/skill.json", lambda d: d.update(description="x" * 1030))
        self.assertTrue(has_error(build.validate(self.root), "expected 40 to 1024"))

    def test_unknown_token(self):
        self.edit_text("skills/pipeline/instructions.md",
                       lambda t: t.replace("{{agent:tester}}", "{{agent:ghost}}", 1))
        self.assertTrue(has_error(build.validate(self.root), "'ghost'"))

    def test_token_for_agent_outside_skill(self):
        self.edit_json("skills/pipeline/skill.json", lambda d: d.update(agents=["architect", "coder"]))
        self.assertTrue(has_error(build.validate(self.root), "'tester' is not listed"))

    def test_orphan_agent_folder(self):
        shutil.copytree(self.root / "agents/coder", self.root / "agents/orphan")
        self.edit_json("agents/orphan/agent.json", lambda d: d.update(name="orphan"))
        self.assertTrue(has_error(build.validate(self.root), "orphan folder"))

    def test_agent_listed_by_two_plugins(self):
        def f(d):
            second = dict(d["plugins"][0])
            second.update(name="other-plugin", skills=[])
            d["plugins"].append(second)
        self.edit_json("catalog.json", f)
        self.assertTrue(has_error(build.validate(self.root), "more than one plugin"))

    def test_non_semver_version(self):
        self.edit_json("catalog.json", lambda d: d["plugins"][0].update(version="1.0"))
        self.assertTrue(has_error(build.validate(self.root), "semver"))

    def test_readme_missing_agent(self):
        self.edit_text("README.md", lambda t: t.replace("`tester`", "tester"))
        self.assertTrue(has_error(build.validate(self.root), "`tester`", "README.md"))

    def test_non_ascii_in_install_ps1(self):
        self.edit_text("install.ps1", lambda t: t + "\n# caf\u00e9\n")
        self.assertTrue(has_error(build.validate(self.root), "non-ASCII", "install.ps1"))


class SyncTest(TempRepoCase):
    def run_check(self):
        return build.main(["--root", str(self.root), "--check"])

    def check_findings(self):
        catalog, _ = build.load_sources(self.root)
        return build.check_outputs(self.root, build.render_outputs(catalog))

    def test_clean_copy_passes(self):
        self.assertEqual(self.check_findings(), [])
        self.assertEqual(self.run_check(), 0)

    def test_modified_generated_file(self):
        self.edit_text("dist/claude-code/dev-pipeline/agents/coder.md", lambda t: t + "extra\n")
        self.assertTrue(has_error(self.check_findings(), "out of date"))
        self.assertEqual(self.run_check(), 1)

    def test_modified_codex_plugin_file(self):
        self.edit_text("dist/codex-plugin/dev-pipeline/plugin.json", lambda t: t.replace("1.0.0", "9.9.9"))
        self.assertTrue(has_error(self.check_findings(), "out of date"))

    def test_modified_codex_marketplace(self):
        self.edit_text(".agents/plugins/marketplace.json", lambda t: t.replace("dev-pipeline", "other", 1))
        self.assertTrue(has_error(self.check_findings(), "out of date"))

    def test_extra_file_under_dist(self):
        (self.root / "dist/codex/dev-pipeline/agents/extra.toml").write_text("x=1\n")
        self.assertTrue(has_error(self.check_findings(), "extra file"))
        (self.root / "dist/codex/dev-pipeline/agents/extra.toml").unlink()
        (self.root / "dist/codex-plugin/dev-pipeline/junk.txt").write_text("x\n")
        self.assertTrue(has_error(self.check_findings(), "extra file"))

    def test_missing_file(self):
        (self.root / "dist/codex/dev-pipeline/agents/tester.toml").unlink()
        self.assertTrue(has_error(self.check_findings(), "missing"))
        self.assertEqual(self.run_check(), 1)

    def test_missing_codex_marketplace(self):
        (self.root / ".agents/plugins/marketplace.json").unlink()
        self.assertTrue(has_error(self.check_findings(), "missing"))

    def test_crlf_copy_still_passes(self):
        rel = "dist/claude-code/dev-pipeline/agents/coder.md"
        p = self.root / rel
        p.write_bytes(p.read_bytes().replace(b"\n", b"\r\n"))
        self.assertEqual(self.check_findings(), [])

    def test_write_mode_removes_stale_and_restores(self):
        (self.root / "dist/codex-plugin/dev-pipeline/junk.txt").write_text("x\n")
        (self.root / "dist/codex/dev-pipeline/agents/coder.toml").unlink()
        self.assertEqual(build.main(["--root", str(self.root)]), 0)
        self.assertEqual(self.run_check(), 0)
        self.assertFalse((self.root / "dist/codex-plugin/dev-pipeline/junk.txt").exists())


class VersionBumpTest(TempRepoCase):
    def git(self, *args):
        r = subprocess.run(["git", *GIT_ID, *args], cwd=str(self.root),
                           capture_output=True, text=True, encoding="utf-8")
        self.assertEqual(r.returncode, 0, r.stderr)
        return r.stdout

    def setUp(self):
        super().setUp()
        self.git("init", "-q", "-b", "main")
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "base")

    def change_prompt_and_build(self):
        self.edit_text("agents/coder/prompt.md", lambda t: t.replace("implement exactly", "implement precisely"))
        self.assertEqual(build.main(["--root", str(self.root)]), 0)
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "change")

    def test_change_without_bump_errors(self):
        self.change_prompt_and_build()
        f = build.check_version_bumps(self.root, "HEAD~1")
        self.assertTrue(has_error(f, "version was not bumped"), f)

    def test_change_with_bump_passes(self):
        self.edit_json("catalog.json", lambda d: d["plugins"][0].update(version="1.0.1"))
        self.change_prompt_and_build()
        self.assertEqual(errors_of(build.check_version_bumps(self.root, "HEAD~1")), [])

    def test_version_decrease_errors(self):
        self.edit_json("catalog.json", lambda d: d["plugins"][0].update(version="0.9.0"))
        self.change_prompt_and_build()
        self.assertTrue(has_error(build.check_version_bumps(self.root, "HEAD~1"), "went down"))

    def test_unknown_ref_warns(self):
        f = build.check_version_bumps(self.root, "no-such-ref")
        self.assertEqual([x.level for x in f], ["WARN"])
        self.assertIn("base ref not found", f[0].message)

    def test_not_a_git_tree_exits_2(self):
        plain = Path(self._tmp) / "plain"
        copy_repo(plain)
        self.assertEqual(build.main(["--root", str(plain), "--base-ref", "HEAD"]), 2)


class RepoFilesTest(unittest.TestCase):
    def test_build_check_cli_exit_0(self):
        r = subprocess.run([sys.executable, str(REPO / "scripts/build.py"), "--check"],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

    def test_license_is_apache_2(self):
        t = read(REPO, "LICENSE")
        for marker in ("Apache License", "Version 2.0, January 2004", "END OF TERMS AND CONDITIONS"):
            self.assertIn(marker, t)

    def test_notice(self):
        t = read(REPO, "NOTICE").replace("\r\n", "\n")
        self.assertIn("gaisser-agents", t)
        self.assertIn("Alejo Gaisser", t)
        self.assertIn("https://github.com/alejogaisser/gaisser-agents", t)

    def test_no_wrong_repo_name(self):
        for rel in ("README.md", "CONTRIBUTING.md", "catalog.json", ".github/workflows/ci.yml",
                    "install.sh", "install.ps1"):
            t = read(REPO, rel)
            self.assertNotIn("gaisser/agents", t, rel)
            self.assertNotIn("alejogaisser/agents", t, rel)

    def test_install_ps1_is_crlf_free_of_bom_and_ascii(self):
        for rel in ("install.sh", "install.ps1", "scripts/build.py"):
            data = (REPO / rel).read_bytes()
            self.assertFalse(data.startswith(b"\xef\xbb\xbf"), rel)
            data.decode("ascii")

    def test_agents_only_documented_in_readme_and_contributing(self):
        self.assertIn("--agents-only", read(REPO, "README.md"))
        self.assertIn("-AgentsOnly", read(REPO, "README.md"))
        self.assertIn("codex-plugin", read(REPO, "CONTRIBUTING.md"))


# --------------------------------------------------------------------------
# Install scripts (temp base folders only; never the real home)
# --------------------------------------------------------------------------
BASH = r"C:\Program Files\Git\bin\bash.exe"


def sh_path(p):
    """Windows path to a form Git Bash accepts."""
    p = str(p).replace("\\", "/")
    if len(p) > 1 and p[1] == ":":
        p = "/" + p[0].lower() + p[2:]
    return p


class InstallBase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.mkdtemp(prefix="ga install ")  # contains a space on purpose
        self.addCleanup(_rmtree, self._tmp)
        self.base = Path(self._tmp) / "my base"
        self.base.mkdir()

    # subclasses implement run(*args) -> (code, out, err)
    def files(self, root):
        return sorted(p.relative_to(root).as_posix() for p in Path(root).rglob("*") if p.is_file())

    def assertSameAsDist(self, installed, dist):
        self.assertEqual(Path(installed).read_bytes(), Path(dist).read_bytes())

    def common_cases(self):
        base = self.base
        # claude install
        code, out, err = self.run_install("claude", "install")
        self.assertEqual(code, 0, out + err)
        self.assertIn("installed", out)
        for a in ("architect", "coder", "tester"):
            self.assertSameAsDist(base / (".claude/agents/%s.md" % a),
                                  REPO / ("dist/claude-code/dev-pipeline/agents/%s.md" % a))
        self.assertSameAsDist(base / ".claude/skills/pipeline/SKILL.md",
                              REPO / "dist/claude-code/dev-pipeline/skills/pipeline/SKILL.md")
        # rerun -> unchanged
        code, out, err = self.run_install("claude", "install")
        self.assertEqual(code, 0, out + err)
        self.assertEqual(out.count("[unchanged]"), 4, out)
        self.assertNotIn("[installed]", out)
        # edit -> skipped, then force -> overwritten + backup
        target = base / ".claude/agents/coder.md"
        original = target.read_bytes()
        target.write_bytes(original + b"\nlocal edit\n")
        code, out, err = self.run_install("claude", "install")
        self.assertEqual(code, 0, out + err)
        self.assertIn("[skipped]", out)
        self.assertEqual(target.read_bytes(), original + b"\nlocal edit\n")
        code, out, err = self.run_install("claude", "force")
        self.assertEqual(code, 0, out + err)
        self.assertIn("overwritten", out)
        self.assertEqual(target.read_bytes(), original)
        backups = list((base / ".claude/agent-catalog-backups").rglob("coder.md"))
        self.assertEqual(len(backups), 1, out)
        self.assertEqual(backups[0].read_bytes(), original + b"\nlocal edit\n")
        # backups are not inside agents/ or skills/
        self.assertFalse(any("backup" in p for p in self.files(base / ".claude/agents")))

    def codex_cases(self):
        base = self.base
        code, out, err = self.run_install("codex", "install")
        self.assertEqual(code, 0, out + err)
        for a in ("architect", "coder", "tester"):
            self.assertSameAsDist(base / (".codex/agents/%s.toml" % a),
                                  REPO / ("dist/codex/dev-pipeline/agents/%s.toml" % a))
        self.assertSameAsDist(base / ".agents/skills/pipeline/SKILL.md",
                              REPO / "dist/codex/dev-pipeline/skills/pipeline/SKILL.md")

    def agents_only_cases(self):
        code, out, err = self.run_install("codex", "agents-only")
        self.assertEqual(code, 0, out + err)
        self.assertEqual(len(list((self.base / ".codex/agents").glob("*.toml"))), 3)
        self.assertFalse((self.base / ".agents").exists(), self.files(self.base))
        self.assertNotIn("skills/", out)
        # agents-only has no effect on the claude target
        code, out, err = self.run_install("claude", "agents-only")
        self.assertEqual(code, 0, out + err)
        self.assertTrue((self.base / ".claude/skills/pipeline/SKILL.md").is_file())

    def dry_run_cases(self):
        code, out, err = self.run_install("all", "dry-run")
        self.assertEqual(code, 0, out + err)
        self.assertIn("[dry-run]", out)
        self.assertEqual(self.files(self.base), [])

    def error_cases(self):
        code, out, err = self.run_install("claude", "bad-plugin")
        self.assertEqual(code, 2, out + err)
        code, out, err = self.run_install("claude", "no-selection")
        self.assertEqual(code, 2, out + err)

    def list_cases(self):
        code, out, err = self.run_install("all", "list")
        self.assertEqual(code, 0, out + err)
        self.assertIn("[claude] dev-pipeline", out)
        self.assertIn("[codex] dev-pipeline", out)
        self.assertIn("agents: architect, coder, tester", out)
        self.assertIn("skills: pipeline", out)
        self.assertEqual(self.files(self.base), [])


@unittest.skipUnless(os.path.isfile(BASH), "Git Bash not found")
class InstallShTest(InstallBase):
    def run_install(self, target, mode):
        args = ["--target", target, "--base", sh_path(self.base)]
        if mode == "install":
            args += ["--plugin", "dev-pipeline"]
        elif mode == "force":
            args += ["--plugin", "dev-pipeline", "--force"]
        elif mode == "agents-only":
            args += ["--plugin", "dev-pipeline", "--agents-only"]
        elif mode == "dry-run":
            args += ["--all", "--dry-run"]
        elif mode == "list":
            args += ["--list"]
        elif mode == "bad-plugin":
            args += ["--plugin", "nope"]
        elif mode == "no-selection":
            pass
        r = subprocess.run([BASH, sh_path(REPO / "install.sh")] + args, capture_output=True,
                           text=True, encoding="utf-8", cwd=str(REPO))
        return r.returncode, r.stdout, r.stderr

    def test_claude_cycle(self):
        self.common_cases()

    def test_codex_install(self):
        self.codex_cases()

    def test_agents_only(self):
        self.agents_only_cases()

    def test_dry_run(self):
        self.dry_run_cases()

    def test_errors(self):
        self.error_cases()

    def test_list(self):
        self.list_cases()

    def test_short_agents_only_flag(self):
        r = subprocess.run([BASH, sh_path(REPO / "install.sh"), "-t", "codex", "-p", "dev-pipeline",
                            "-A", "-b", sh_path(self.base)],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertFalse((self.base / ".agents").exists())

    def test_codex_home_env_split(self):
        home = Path(self._tmp) / "h"
        ch = Path(self._tmp) / "c"
        home.mkdir()
        ch.mkdir()
        env = dict(os.environ, HOME=sh_path(home), CODEX_HOME=sh_path(ch))
        r = subprocess.run([BASH, sh_path(REPO / "install.sh"), "--target", "codex",
                            "--plugin", "dev-pipeline"],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO), env=env)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertEqual(len(list((ch / "agents").glob("*.toml"))), 3, self.files(self._tmp))
        self.assertTrue((home / ".agents/skills/pipeline/SKILL.md").is_file(), self.files(self._tmp))
        self.assertFalse((home / ".codex").exists())

    def test_refuses_filesystem_root(self):
        r = subprocess.run([BASH, sh_path(REPO / "install.sh"), "--plugin", "dev-pipeline",
                            "--dry-run", "--base", "/"],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
        self.assertEqual(r.returncode, 2, r.stdout + r.stderr)


POWERSHELL = "powershell.exe"


@unittest.skipUnless(sys.platform == "win32" and shutil.which(POWERSHELL), "Windows PowerShell not found")
class InstallPs1Test(InstallBase):
    def ps(self, *args, env=None):
        cmd = [POWERSHELL, "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
               str(REPO / "install.ps1")] + list(args)
        r = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8",
                           cwd=str(REPO), env=env)
        return r.returncode, r.stdout, r.stderr

    def run_install(self, target, mode):
        args = ["-Target", target, "-Base", str(self.base)]
        if mode == "install":
            args += ["-Plugin", "dev-pipeline"]
        elif mode == "force":
            args += ["-Plugin", "dev-pipeline", "-Force"]
        elif mode == "agents-only":
            args += ["-Plugin", "dev-pipeline", "-AgentsOnly"]
        elif mode == "dry-run":
            args += ["-All", "-DryRun"]
        elif mode == "list":
            args += ["-List"]
        elif mode == "bad-plugin":
            args += ["-Plugin", "nope"]
        return self.ps(*args)

    def test_claude_cycle(self):
        self.common_cases()

    def test_codex_install(self):
        self.codex_cases()

    def test_agents_only(self):
        self.agents_only_cases()

    def test_dry_run(self):
        self.dry_run_cases()

    def test_errors(self):
        self.error_cases()

    def test_list(self):
        self.list_cases()

    def test_codex_home_env_split(self):
        home = Path(self._tmp) / "h"
        ch = Path(self._tmp) / "c"
        home.mkdir()
        ch.mkdir()
        # -Base omitted means the real $HOME would be used for the skill, so only dry-run here.
        env = dict(os.environ, CODEX_HOME=str(ch))
        code, out, err = self.ps("-Target", "codex", "-Plugin", "dev-pipeline", "-DryRun", env=env)
        self.assertEqual(code, 0, out + err)
        self.assertIn("agents/architect.toml", out)
        self.assertEqual(self.files(ch), [])


if __name__ == "__main__":
    unittest.main()
