"""Tests for scripts/build.py, per docs/plan.md (multi-team plan), section 9.

Run from the repository root:
    py -3 -m unittest discover -s scripts/tests -v
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))
import build  # noqa: E402

GIT_ID = ["-c", "user.name=test", "-c", "user.email=test@example.com"]
PLUGIN = "gaisser-agents"
AGENTS = ("dev-architect", "dev-coder", "dev-tester")


def _rmtree(path):
    def onerr(func, p, exc):
        os.chmod(p, 0o700)
        func(p)
    shutil.rmtree(path, onerror=onerr)


def copy_repo(dest):
    """Copy the repository (without .git and caches) into dest."""
    shutil.copytree(
        REPO, dest, dirs_exist_ok=True,
        ignore=shutil.ignore_patterns(".git", "__pycache__", "tests"),
    )
    return Path(dest)


def errors_of(findings):
    return [f for f in findings if f.level == "ERROR"]


def has_error(findings, text, path=None):
    return any(
        text in f.message and (path is None or f.path == path)
        for f in errors_of(findings)
    )


def read(root, rel):
    return (Path(root) / rel).read_bytes().decode("utf-8")


class TempRepoCase(unittest.TestCase):
    """Each test gets a fresh copy of the repository in a temp folder."""

    def setUp(self):
        self._tmp = tempfile.mkdtemp(prefix="ga-test-")
        self.addCleanup(_rmtree, self._tmp)
        self.root = copy_repo(Path(self._tmp) / "repo")

    def edit_json(self, rel, fn):
        p = self.root / rel
        data = json.loads(p.read_text(encoding="utf-8"))
        fn(data)
        p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")

    def edit_text(self, rel, fn):
        p = self.root / rel
        text = p.read_bytes().decode("utf-8")
        p.write_bytes(fn(text).encode("utf-8"))


class OutputsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        catalog, findings = build.load_sources(REPO)
        assert catalog is not None, findings
        cls.outputs = build.render_outputs(catalog)
        cls.catalog = catalog

    def test_repo_validates_clean(self):
        self.assertEqual(errors_of(build.validate(REPO)), [])

    def test_generated_file_set(self):
        expected = {
            ".claude-plugin/marketplace.json",
            ".agents/plugins/marketplace.json",
            "dist/claude-code/gaisser-agents/.claude-plugin/plugin.json",
            "dist/claude-code/gaisser-agents/skills/dev-team/SKILL.md",
            "dist/codex/gaisser-agents/skills/dev-team/SKILL.md",
            "dist/codex-plugin/gaisser-agents/plugin.json",
            "dist/codex-plugin/gaisser-agents/skills/dev-team/SKILL.md",
        }
        for a in AGENTS:
            expected.add("dist/claude-code/gaisser-agents/agents/%s.md" % a)
            expected.add("dist/codex/gaisser-agents/agents/%s.toml" % a)
        self.assertEqual(set(self.outputs), expected)

    def test_architect_claude_matches_plan_8_3(self):
        text = self.outputs["dist/claude-code/gaisser-agents/agents/dev-architect.md"]
        want = (
            "---\n"
            "name: dev-architect\n"
            'description: "Designs the solution before any code is written and saves an '
            "implementation plan to docs/plan.md: a handoff with testable acceptance criteria, "
            "then design, risks, and steps. Keeps the project's decision records and lessons "
            "learned. Use proactively for new features, refactors, and architecture decisions. "
            'Never edits project code."\n'
            "tools: Read, Grep, Glob, Edit, Write, WebFetch, WebSearch\n"
            "model: opus\n"
            "effort: high\n"
            "color: blue\n"
            "---\n\n"
            "You are a senior software architect. You read the relevant code and turn a request "
            "into an implementation plan that a coder can execute without guessing. "
            "You never write project code.\n"
        )
        self.assertTrue(text.startswith(want), text[:600])
        self.assertTrue(read(REPO, "dist/claude-code/gaisser-agents/agents/dev-architect.md").startswith(want))

    def test_architect_codex_matches_plan_8_3(self):
        want = (
            "# Generated by scripts/build.py from teams/dev-team/agents/dev-architect/ in "
            "https://github.com/alejogaisser/gaisser-agents. Do not edit.\n"
            "# License: Apache-2.0. See the NOTICE file in the repository.\n"
            'name = "dev_architect"\n'
            'description = "Designs the solution before any code is written and saves an '
            "implementation plan to docs/plan.md: a handoff with testable acceptance criteria, "
            "then design, risks, and steps. Keeps the project's decision records and lessons "
            "learned. Use proactively for new features, refactors, and architecture decisions. "
            'Never edits project code."\n'
            'model_reasoning_effort = "high"\n'
            'sandbox_mode = "workspace-write"\n'
            'developer_instructions = """\n'
            "You are a senior software architect. You read the relevant code and turn a request "
            "into an implementation plan that a coder can execute without guessing. "
            "You never write project code.\n"
        )
        self.assertTrue(self.outputs["dist/codex/gaisser-agents/agents/dev-architect.toml"].startswith(want))
        self.assertTrue(read(REPO, "dist/codex/gaisser-agents/agents/dev-architect.toml").startswith(want))

    def test_coder_and_tester_mappings(self):
        cases = {
            "dev-coder": ("Read, Grep, Glob, Edit, Write, NotebookEdit, Bash, PowerShell, LSP",
                      "sonnet", "medium"),
            "dev-tester": ("Read, Grep, Glob, Edit, Write, Bash, PowerShell", "sonnet", "medium"),
        }
        for name, (tools, model, effort) in cases.items():
            md = self.outputs["dist/claude-code/gaisser-agents/agents/%s.md" % name]
            self.assertIn("\ntools: %s\n" % tools, md)
            self.assertIn("\nmodel: %s\n" % model, md)
            self.assertIn("\neffort: %s\n" % effort, md)
            data = tomllib.loads(self.outputs["dist/codex/gaisser-agents/agents/%s.toml" % name])
            self.assertEqual(data["sandbox_mode"], "workspace-write")
            self.assertEqual(data["model_reasoning_effort"], effort)
            self.assertNotIn("model", data)

    def test_codex_toml_roundtrip_equals_prompt(self):
        for name in AGENTS:
            data = tomllib.loads(self.outputs["dist/codex/gaisser-agents/agents/%s.toml" % name])
            prompt = build.normalize_body((REPO / "teams" / "dev-team" / "agents" / name / "prompt.md").read_text(encoding="utf-8"))
            self.assertEqual(data["developer_instructions"], prompt)
            self.assertEqual(data["name"], build.codex_agent_name(name))

    def test_token_rendering_differs_per_tool(self):
        claude = self.outputs["dist/claude-code/gaisser-agents/skills/dev-team/SKILL.md"]
        codex = self.outputs["dist/codex/gaisser-agents/skills/dev-team/SKILL.md"]
        for a in AGENTS:
            self.assertIn("| `gaisser-agents:%s` |" % a, claude)
            self.assertIn("| `%s` |" % a.replace("-", "_"), codex)
            self.assertNotIn("gaisser-agents:%s" % a, codex)
            self.assertNotIn("dev-team:%s" % a, claude)
        self.assertNotIn("{{", claude)
        self.assertNotIn("{{", codex)

    def test_skill_frontmatter_fields(self):
        def fm_keys(text):
            lines = text.split("\n")
            self.assertEqual(lines[0], "---")
            end = lines.index("---", 1)
            return [ln.split(":", 1)[0] for ln in lines[1:end]]

        claude = self.outputs["dist/claude-code/gaisser-agents/skills/dev-team/SKILL.md"]
        codex = self.outputs["dist/codex/gaisser-agents/skills/dev-team/SKILL.md"]
        self.assertEqual(fm_keys(claude), ["name", "description", "argument-hint", "license"])
        self.assertEqual(fm_keys(codex), ["name", "description", "license"])

    def test_marketplace_and_plugin_json(self):
        mp = json.loads(self.outputs[".claude-plugin/marketplace.json"])
        self.assertEqual(mp["name"], "gaisser-agents")
        self.assertEqual(mp["plugins"][0]["source"], "./dist/claude-code/gaisser-agents")
        pj = json.loads(self.outputs["dist/claude-code/gaisser-agents/.claude-plugin/plugin.json"])
        self.assertEqual(pj["license"], "Apache-2.0")
        self.assertTrue(pj["homepage"].endswith("#gaisser-agents"))
        self.assertEqual(len(mp["plugins"]), 1)
        self.assertEqual(mp["plugins"][0]["name"], "gaisser-agents")
        self.assertEqual(pj["name"], "gaisser-agents")
        self.assertEqual(pj["version"], json.loads(read(REPO, "catalog.json"))["plugin"]["version"])
        self.assertEqual(pj["repository"], "https://github.com/alejogaisser/gaisser-agents")

    def test_outputs_are_lf_and_end_with_newline(self):
        for path, content in self.outputs.items():
            self.assertNotIn("\r", content, path)
            self.assertTrue(content.endswith("\n"), path)
            self.assertFalse(content.endswith("\n\n"), path)


class CodexPluginTest(unittest.TestCase):
    """Section 18 addendum."""

    @classmethod
    def setUpClass(cls):
        catalog, _ = build.load_sources(REPO)
        cls.outputs = build.render_outputs(catalog)

    def test_plugin_outputs_generated_and_in_sync_on_disk(self):
        for rel in ("dist/codex-plugin/gaisser-agents/plugin.json",
                    "dist/codex-plugin/gaisser-agents/skills/dev-team/SKILL.md",
                    ".agents/plugins/marketplace.json"):
            self.assertTrue((REPO / rel).is_file(), rel)
            self.assertEqual(read(REPO, rel).replace("\r\n", "\n"), self.outputs[rel], rel)

    def test_codex_plugin_skill_equals_codex_skill(self):
        self.assertEqual(
            read(REPO, "dist/codex-plugin/gaisser-agents/skills/dev-team/SKILL.md"),
            read(REPO, "dist/codex/gaisser-agents/skills/dev-team/SKILL.md"),
        )

    def test_plugin_json_fields(self):
        pj = json.loads(read(REPO, "dist/codex-plugin/gaisser-agents/plugin.json"))
        self.assertEqual(pj["name"], "gaisser-agents")
        self.assertEqual(pj["version"], json.loads(read(REPO, "catalog.json"))["plugin"]["version"])
        self.assertEqual(pj["license"], "Apache-2.0")
        self.assertTrue(pj["homepage"].endswith("#gaisser-agents"))
        self.assertIn("author", pj)
        self.assertIn("description", pj)

    def test_codex_marketplace_source_path_exists_and_relative(self):
        mp = json.loads(read(REPO, ".agents/plugins/marketplace.json"))
        self.assertEqual(mp["name"], "gaisser-agents")
        self.assertEqual(len(mp["plugins"]), 1)
        entry = [p for p in mp["plugins"] if p["name"] == "gaisser-agents"]
        self.assertEqual(len(entry), 1)
        self.assertEqual(entry[0]["source"]["path"], "./dist/codex-plugin/gaisser-agents")
        path = entry[0]["source"]["path"]
        self.assertTrue(path.startswith("./"), path)
        self.assertNotIn("..", path)
        self.assertNotIn("\\", path)
        target = REPO / path
        self.assertTrue(target.is_dir(), path)
        self.assertTrue((target / "plugin.json").is_file())
        self.assertTrue((target / "skills" / "dev-team" / "SKILL.md").is_file())

    def test_codex_plugin_carries_no_agents(self):
        self.assertFalse((REPO / "dist/codex-plugin/gaisser-agents/agents").exists())


class EscapingTest(unittest.TestCase):
    def test_triple_quotes_and_backslashes_roundtrip(self):
        body = 'path C:\\dir\\n and """triple""" and "" and \\"""\nline two\\\n'
        body = build.normalize_body(body)
        toml = 'developer_instructions = """\n' + build.toml_escape_ml(body) + '"""\n'
        self.assertEqual(tomllib.loads(toml)["developer_instructions"], body)

    def test_dq_roundtrip_in_toml(self):
        s = 'He said "hi" \\ and \\n'
        self.assertEqual(tomllib.loads("k = " + build.dq(s) + "\n")["k"], s)


class SourceValidationTest(TempRepoCase):
    def test_baseline_clean(self):
        self.assertEqual(errors_of(build.validate(self.root)), [])

    def agent_edit(self, name, fn):
        self.edit_json("teams/dev-team/agents/%s/agent.json" % name, fn)

    def test_unknown_key_in_agent_json(self):
        self.agent_edit("dev-coder", lambda d: d.update(bogus=1))
        self.assertTrue(has_error(build.validate(self.root), "unknown key 'bogus'"))

    def test_unknown_capability(self):
        self.agent_edit("dev-coder", lambda d: d["capabilities"].append("teleport"))
        self.assertTrue(has_error(build.validate(self.root), "capabilities"))

    def test_capabilities_without_read(self):
        self.agent_edit("dev-coder", lambda d: d.update(capabilities=["edit", "shell"]))
        self.assertTrue(has_error(build.validate(self.root), "must include 'read'"))

    def test_fast_tier_with_effort(self):
        self.agent_edit("dev-coder", lambda d: d.update(model="fast", effort="low"))
        self.assertTrue(has_error(build.validate(self.root), "must not set effort"))

    def test_effort_optional_for_deep(self):
        self.agent_edit("dev-architect", lambda d: d.pop("effort"))
        findings = build.validate(self.root)
        self.assertFalse(has_error(findings, "effort is required"))
        catalog, _ = build.load_sources(self.root)
        outputs = build.render_outputs(catalog)
        self.assertNotIn("\neffort:", outputs["dist/claude-code/gaisser-agents/agents/dev-architect.md"])
        self.assertNotIn("model_reasoning_effort", outputs["dist/codex/gaisser-agents/agents/dev-architect.toml"])

    def test_description_without_use(self):
        self.agent_edit("dev-coder", lambda d: d.update(
            description="Implements a plan step by step following the project conventions closely."))
        self.assertTrue(has_error(build.validate(self.root), "'Use '"))

    def test_description_too_long(self):
        self.agent_edit("dev-coder", lambda d: d.update(description="Use " + "x" * 420))
        self.assertTrue(has_error(build.validate(self.root), "expected 40 to 400"))

    def test_name_differs_from_folder(self):
        self.agent_edit("dev-coder", lambda d: d.update(name="dev-coder2"))
        self.assertTrue(has_error(build.validate(self.root), "must equal the folder name"))

    def test_reserved_name_worker(self):
        agents = self.root / "teams/dev-team/agents"
        shutil.move(str(agents / "dev-coder"), str(agents / "worker"))
        self.edit_json("teams/dev-team/agents/worker/agent.json", lambda d: d.update(name="worker"))
        self.assertTrue(has_error(build.validate(self.root), "reserved Codex name"))

    def test_prompt_missing_boundaries_heading(self):
        self.edit_text("teams/dev-team/agents/dev-tester/prompt.md", lambda t: t.replace("## Boundaries", "## Limits"))
        self.assertTrue(has_error(build.validate(self.root), "## Boundaries"))

    def test_prompt_missing_boundary_phrase(self):
        self.edit_text("teams/dev-team/agents/dev-tester/prompt.md",
                       lambda t: t.replace("You cannot ask the user questions", "You may ask"))
        self.assertTrue(has_error(build.validate(self.root), "boundary phrase"))

    def test_prompt_with_webfetch(self):
        self.edit_text("teams/dev-team/agents/dev-tester/prompt.md", lambda t: t.replace("Process", "Process WebFetch", 1))
        self.assertTrue(has_error(build.validate(self.root), "WebFetch"))

    def test_prompt_with_braces(self):
        self.edit_text("teams/dev-team/agents/dev-tester/prompt.md", lambda t: t.rstrip("\n") + "\n{{x}}\n")
        self.assertTrue(has_error(build.validate(self.root), "{{"))

    def test_skill_description_too_long(self):
        self.edit_json("teams/dev-team/skills/dev-team/skill.json", lambda d: d.update(description="x" * 1030))
        self.assertTrue(has_error(build.validate(self.root), "expected 40 to 1024"))

    def test_unknown_token(self):
        self.edit_text("teams/dev-team/skills/dev-team/instructions.md",
                       lambda t: t.replace("{{agent:dev-tester}}", "{{agent:ghost}}", 1))
        self.assertTrue(has_error(build.validate(self.root), "'ghost'"))

    def test_token_for_agent_outside_skill(self):
        self.edit_json("teams/dev-team/skills/dev-team/skill.json", lambda d: d.update(agents=["dev-architect", "dev-coder"]))
        self.assertTrue(has_error(build.validate(self.root), "'dev-tester' is not listed"))

    def test_orphan_team_folder(self):
        shutil.copytree(self.root / "teams/dev-team", self.root / "teams/spare-team")
        self.edit_json("teams/spare-team/team.json", lambda d: d.update(name="spare-team"))
        self.assertTrue(has_error(build.validate(self.root), "orphan team folder"))

    def test_agent_name_in_two_teams(self):
        shutil.copytree(self.root / "teams/dev-team", self.root / "teams/other-team")
        shutil.move(str(self.root / "teams/other-team/skills/dev-team"),
                    str(self.root / "teams/other-team/skills/other-team"))
        self.edit_json("teams/other-team/team.json", lambda d: d.update(name="other-team"))
        self.edit_json("teams/other-team/skills/other-team/skill.json",
                       lambda d: d.update(name="other-team"))
        self.edit_json("catalog.json", lambda d: d["teams"].append("other-team"))
        self.assertTrue(has_error(build.validate(self.root), "is defined by more than one team"))

    def test_non_semver_version(self):
        self.edit_json("catalog.json", lambda d: d["plugin"].update(version="1.0"))
        self.assertTrue(has_error(build.validate(self.root), "semver"))

    def test_readme_missing_agent(self):
        self.edit_text("README.md", lambda t: t.replace("`dev-tester`", "dev-tester"))
        self.assertTrue(has_error(build.validate(self.root), "`dev-tester`", "README.md"))

    def test_non_ascii_in_install_ps1(self):
        self.edit_text("install.ps1", lambda t: t + "\n# caf\u00e9\n")
        self.assertTrue(has_error(build.validate(self.root), "non-ASCII", "install.ps1"))


class SyncTest(TempRepoCase):
    def run_check(self):
        return build.main(["--root", str(self.root), "--check"])

    def check_findings(self):
        catalog, _ = build.load_sources(self.root)
        return build.check_outputs(self.root, build.render_outputs(catalog))

    def test_clean_copy_passes(self):
        self.assertEqual(self.check_findings(), [])
        self.assertEqual(self.run_check(), 0)

    def test_modified_generated_file(self):
        self.edit_text("dist/claude-code/gaisser-agents/agents/dev-coder.md", lambda t: t + "extra\n")
        self.assertTrue(has_error(self.check_findings(), "out of date"))
        self.assertEqual(self.run_check(), 1)

    def test_modified_codex_plugin_file(self):
        self.edit_text("dist/codex-plugin/gaisser-agents/plugin.json", lambda t: t.replace("3.0.0", "9.9.9"))
        self.assertTrue(has_error(self.check_findings(), "out of date"))

    def test_modified_codex_marketplace(self):
        self.edit_text(".agents/plugins/marketplace.json", lambda t: t.replace("gaisser-agents", "other", 1))
        self.assertTrue(has_error(self.check_findings(), "out of date"))

    def test_extra_file_under_dist(self):
        (self.root / "dist/codex/gaisser-agents/agents/extra.toml").write_text("x=1\n")
        self.assertTrue(has_error(self.check_findings(), "extra file"))
        (self.root / "dist/codex/gaisser-agents/agents/extra.toml").unlink()
        (self.root / "dist/codex-plugin/gaisser-agents/junk.txt").write_text("x\n")
        self.assertTrue(has_error(self.check_findings(), "extra file"))

    def test_missing_file(self):
        (self.root / "dist/codex/gaisser-agents/agents/dev-tester.toml").unlink()
        self.assertTrue(has_error(self.check_findings(), "missing"))
        self.assertEqual(self.run_check(), 1)

    def test_missing_codex_marketplace(self):
        (self.root / ".agents/plugins/marketplace.json").unlink()
        self.assertTrue(has_error(self.check_findings(), "missing"))

    def test_crlf_copy_still_passes(self):
        rel = "dist/claude-code/gaisser-agents/agents/dev-coder.md"
        p = self.root / rel
        p.write_bytes(p.read_bytes().replace(b"\n", b"\r\n"))
        self.assertEqual(self.check_findings(), [])

    def test_write_mode_removes_stale_and_restores(self):
        (self.root / "dist/codex-plugin/gaisser-agents/junk.txt").write_text("x\n")
        (self.root / "dist/codex/gaisser-agents/agents/dev-coder.toml").unlink()
        self.assertEqual(build.main(["--root", str(self.root)]), 0)
        self.assertEqual(self.run_check(), 0)
        self.assertFalse((self.root / "dist/codex-plugin/gaisser-agents/junk.txt").exists())


class VersionBumpTest(TempRepoCase):
    def git(self, *args):
        r = subprocess.run(["git", *GIT_ID, *args], cwd=str(self.root),
                           capture_output=True, text=True, encoding="utf-8")
        self.assertEqual(r.returncode, 0, r.stderr)
        return r.stdout

    def setUp(self):
        super().setUp()
        self.git("init", "-q", "-b", "main")
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "base")

    def change_prompt_and_build(self):
        self.edit_text("teams/dev-team/agents/dev-coder/prompt.md", lambda t: t.replace("implement exactly", "implement precisely"))
        self.assertEqual(build.main(["--root", str(self.root)]), 0)
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "change")

    def test_change_without_bump_errors(self):
        self.change_prompt_and_build()
        f = build.check_version_bumps(self.root, "HEAD~1")
        self.assertTrue(has_error(f, "plugin.version was not bumped", "catalog.json"), f)

    def test_change_with_bump_passes(self):
        self.edit_json("catalog.json", lambda d: d["plugin"].update(version="3.0.1"))
        self.change_prompt_and_build()
        self.assertEqual(errors_of(build.check_version_bumps(self.root, "HEAD~1")), [])

    def test_version_decrease_errors(self):
        self.edit_json("catalog.json", lambda d: d["plugin"].update(version="2.9.0"))
        self.change_prompt_and_build()
        self.assertTrue(has_error(build.check_version_bumps(self.root, "HEAD~1"),
                                  "plugin.version went down", "catalog.json"))

    def test_unknown_ref_warns(self):
        f = build.check_version_bumps(self.root, "no-such-ref")
        self.assertEqual([x.level for x in f], ["WARN"])
        self.assertIn("base ref not found", f[0].message)

    def test_not_a_git_tree_exits_2(self):
        plain = Path(self._tmp) / "plain"
        copy_repo(plain)
        self.assertEqual(build.main(["--root", str(plain), "--base-ref", "HEAD"]), 2)


class RepoFilesTest(unittest.TestCase):
    def test_build_check_cli_exit_0(self):
        r = subprocess.run([sys.executable, str(REPO / "scripts/build.py"), "--check"],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

    def test_license_is_apache_2(self):
        t = read(REPO, "LICENSE")
        for marker in ("Apache License", "Version 2.0, January 2004", "END OF TERMS AND CONDITIONS"):
            self.assertIn(marker, t)

    def test_notice(self):
        t = read(REPO, "NOTICE").replace("\r\n", "\n")
        self.assertIn("gaisser-agents", t)
        self.assertIn("Alejo Gaisser", t)
        self.assertIn("https://github.com/alejogaisser/gaisser-agents", t)

    def test_no_wrong_repo_name(self):
        for rel in ("README.md", "CONTRIBUTING.md", "catalog.json", ".github/workflows/ci.yml",
                    "install.sh", "install.ps1"):
            t = read(REPO, rel)
            self.assertNotIn("gaisser/agents", t, rel)
            self.assertNotIn("alejogaisser/agents", t, rel)

    def test_install_ps1_is_crlf_free_of_bom_and_ascii(self):
        for rel in ("install.sh", "install.ps1", "scripts/build.py"):
            data = (REPO / rel).read_bytes()
            self.assertFalse(data.startswith(b"\xef\xbb\xbf"), rel)
            data.decode("ascii")

    def test_agents_only_documented_in_readme_and_contributing(self):
        self.assertIn("--agents-only", read(REPO, "README.md"))
        self.assertIn("-AgentsOnly", read(REPO, "README.md"))
        self.assertIn("codex-plugin", read(REPO, "CONTRIBUTING.md"))


# --------------------------------------------------------------------------
# Install scripts (temp base folders only; never the real home)
# --------------------------------------------------------------------------
BASH = r"C:\Program Files\Git\bin\bash.exe"


def sh_path(p):
    """Windows path to a form Git Bash accepts."""
    p = str(p).replace("\\", "/")
    if len(p) > 1 and p[1] == ":":
        p = "/" + p[0].lower() + p[2:]
    return p


class InstallBase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.mkdtemp(prefix="ga install ")  # contains a space on purpose
        self.addCleanup(_rmtree, self._tmp)
        self.base = Path(self._tmp) / "my base"
        self.base.mkdir()

    # subclasses implement run(*args) -> (code, out, err)
    def files(self, root):
        return sorted(p.relative_to(root).as_posix() for p in Path(root).rglob("*") if p.is_file())

    def assertSameAsDist(self, installed, dist):
        self.assertEqual(Path(installed).read_bytes(), Path(dist).read_bytes())

    def common_cases(self):
        base = self.base
        # claude install
        code, out, err = self.run_install("claude", "install")
        self.assertEqual(code, 0, out + err)
        self.assertIn("installed", out)
        for a in AGENTS:
            self.assertSameAsDist(base / (".claude/agents/%s.md" % a),
                                  REPO / ("dist/claude-code/gaisser-agents/agents/%s.md" % a))
        self.assertSameAsDist(base / ".claude/skills/dev-team/SKILL.md",
                              REPO / "dist/claude-code/gaisser-agents/skills/dev-team/SKILL.md")
        # rerun -> unchanged
        code, out, err = self.run_install("claude", "install")
        self.assertEqual(code, 0, out + err)
        self.assertEqual(out.count("[unchanged]"), 4, out)
        self.assertNotIn("[installed]", out)
        # edit -> skipped, then force -> overwritten + backup
        target = base / ".claude/agents/dev-coder.md"
        original = target.read_bytes()
        target.write_bytes(original + b"\nlocal edit\n")
        code, out, err = self.run_install("claude", "install")
        self.assertEqual(code, 0, out + err)
        self.assertIn("[skipped]", out)
        self.assertEqual(target.read_bytes(), original + b"\nlocal edit\n")
        code, out, err = self.run_install("claude", "force")
        self.assertEqual(code, 0, out + err)
        self.assertIn("overwritten", out)
        self.assertEqual(target.read_bytes(), original)
        backups = list((base / ".claude/agent-catalog-backups").rglob("dev-coder.md"))
        self.assertEqual(len(backups), 1, out)
        self.assertEqual(backups[0].read_bytes(), original + b"\nlocal edit\n")
        # backups are not inside agents/ or skills/
        self.assertFalse(any("backup" in p for p in self.files(base / ".claude/agents")))

    def codex_cases(self):
        base = self.base
        code, out, err = self.run_install("codex", "install")
        self.assertEqual(code, 0, out + err)
        for a in AGENTS:
            self.assertSameAsDist(base / (".codex/agents/%s.toml" % a),
                                  REPO / ("dist/codex/gaisser-agents/agents/%s.toml" % a))
        self.assertSameAsDist(base / ".agents/skills/dev-team/SKILL.md",
                              REPO / "dist/codex/gaisser-agents/skills/dev-team/SKILL.md")

    def agents_only_cases(self):
        code, out, err = self.run_install("codex", "agents-only")
        self.assertEqual(code, 0, out + err)
        self.assertEqual(len(list((self.base / ".codex/agents").glob("*.toml"))), 3)
        self.assertFalse((self.base / ".agents").exists(), self.files(self.base))
        self.assertNotIn("skills/", out)
        # agents-only has no effect on the claude target
        code, out, err = self.run_install("claude", "agents-only")
        self.assertEqual(code, 0, out + err)
        self.assertTrue((self.base / ".claude/skills/dev-team/SKILL.md").is_file())

    def dry_run_cases(self):
        code, out, err = self.run_install("all", "dry-run")
        self.assertEqual(code, 0, out + err)
        self.assertIn("[dry-run]", out)
        self.assertEqual(self.files(self.base), [])

    def error_cases(self):
        code, out, err = self.run_install("claude", "bad-plugin")
        self.assertEqual(code, 2, out + err)
        code, out, err = self.run_install("claude", "no-selection")
        self.assertEqual(code, 2, out + err)

    def list_cases(self):
        code, out, err = self.run_install("all", "list")
        self.assertEqual(code, 0, out + err)
        self.assertRegex(out, r"\[claude\] gaisser-agents\s+agents: dev-architect, dev-coder, dev-tester\s+skills: dev-team")
        self.assertRegex(out, r"\[codex\] gaisser-agents\s+agents: dev-architect, dev-coder, dev-tester\s+skills: dev-team")
        self.assertEqual(self.files(self.base), [])


@unittest.skipUnless(os.path.isfile(BASH), "Git Bash not found")
class InstallShTest(InstallBase):
    def run_install(self, target, mode):
        args = ["--target", target, "--base", sh_path(self.base)]
        if mode == "install":
            args += ["--plugin", "gaisser-agents"]
        elif mode == "force":
            args += ["--plugin", "gaisser-agents", "--force"]
        elif mode == "agents-only":
            args += ["--plugin", "gaisser-agents", "--agents-only"]
        elif mode == "dry-run":
            args += ["--all", "--dry-run"]
        elif mode == "list":
            args += ["--list"]
        elif mode == "bad-plugin":
            args += ["--plugin", "nope"]
        elif mode == "no-selection":
            pass
        r = subprocess.run([BASH, sh_path(REPO / "install.sh")] + args, capture_output=True,
                           text=True, encoding="utf-8", cwd=str(REPO))
        return r.returncode, r.stdout, r.stderr

    def test_claude_cycle(self):
        self.common_cases()

    def test_codex_install(self):
        self.codex_cases()

    def test_agents_only(self):
        self.agents_only_cases()

    def test_dry_run(self):
        self.dry_run_cases()

    def test_errors(self):
        self.error_cases()

    def test_list(self):
        self.list_cases()

    def test_short_agents_only_flag(self):
        r = subprocess.run([BASH, sh_path(REPO / "install.sh"), "-t", "codex", "-p", "gaisser-agents",
                            "-A", "-b", sh_path(self.base)],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertFalse((self.base / ".agents").exists())

    def test_codex_home_env_split(self):
        home = Path(self._tmp) / "h"
        ch = Path(self._tmp) / "c"
        home.mkdir()
        ch.mkdir()
        env = dict(os.environ, HOME=sh_path(home), CODEX_HOME=sh_path(ch))
        r = subprocess.run([BASH, sh_path(REPO / "install.sh"), "--target", "codex",
                            "--plugin", "gaisser-agents"],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO), env=env)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertEqual(len(list((ch / "agents").glob("*.toml"))), 3, self.files(self._tmp))
        self.assertTrue((home / ".agents/skills/dev-team/SKILL.md").is_file(), self.files(self._tmp))
        self.assertFalse((home / ".codex").exists())

    def test_refuses_filesystem_root(self):
        r = subprocess.run([BASH, sh_path(REPO / "install.sh"), "--plugin", "gaisser-agents",
                            "--dry-run", "--base", "/"],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
        self.assertEqual(r.returncode, 2, r.stdout + r.stderr)


POWERSHELL = "powershell.exe"


@unittest.skipUnless(sys.platform == "win32" and shutil.which(POWERSHELL), "Windows PowerShell not found")
class InstallPs1Test(InstallBase):
    def ps(self, *args, env=None):
        cmd = [POWERSHELL, "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
               str(REPO / "install.ps1")] + list(args)
        r = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8",
                           cwd=str(REPO), env=env)
        return r.returncode, r.stdout, r.stderr

    def run_install(self, target, mode):
        args = ["-Target", target, "-Base", str(self.base)]
        if mode == "install":
            args += ["-Plugin", "gaisser-agents"]
        elif mode == "force":
            args += ["-Plugin", "gaisser-agents", "-Force"]
        elif mode == "agents-only":
            args += ["-Plugin", "gaisser-agents", "-AgentsOnly"]
        elif mode == "dry-run":
            args += ["-All", "-DryRun"]
        elif mode == "list":
            args += ["-List"]
        elif mode == "bad-plugin":
            args += ["-Plugin", "nope"]
        return self.ps(*args)

    def test_claude_cycle(self):
        self.common_cases()

    def test_codex_install(self):
        self.codex_cases()

    def test_agents_only(self):
        self.agents_only_cases()

    def test_dry_run(self):
        self.dry_run_cases()

    def test_errors(self):
        self.error_cases()

    def test_list(self):
        self.list_cases()

    def test_codex_home_env_split(self):
        home = Path(self._tmp) / "h"
        ch = Path(self._tmp) / "c"
        home.mkdir()
        ch.mkdir()
        # -Base omitted means the real $HOME would be used for the skill, so only dry-run here.
        env = dict(os.environ, CODEX_HOME=str(ch))
        code, out, err = self.ps("-Target", "codex", "-Plugin", "gaisser-agents", "-DryRun", env=env)
        self.assertEqual(code, 0, out + err)
        self.assertIn("agents/dev-architect.toml", out)
        self.assertEqual(self.files(ch), [])


# --------------------------------------------------------------------------
# New tests: plan section 9.2 (T1 to T20, T30 to T34) and 9.2b (T21 to T29)
# --------------------------------------------------------------------------
import re  # noqa: E402


def warns_of(findings):
    return [f for f in findings if f.level == "WARN"]


def has_warn(findings, text):
    return any(text in f.message for f in warns_of(findings))


DEV = "teams/dev-team"


class TeamFixture(TempRepoCase):
    """Adds helpers to build extra teams inside the temp copy."""

    def add_team(self, name, targets, agent=None, prefix=None, readme=True, caps=None):
        root = self.root
        if prefix is None:
            prefix = name[:-len("-team")] + "-" if name.endswith("-team") else name + "-"
        if agent is None:
            agent = prefix + "helper"
        tdir = root / "teams" / name
        (tdir / "agents").mkdir(parents=True)
        (tdir / "skills" / name).mkdir(parents=True)
        meta = {
            "name": name, "displayName": name.replace("-", " ").title(),
            "description": "Fixture team used by the tests, with one helper agent and one entry skill.",
            "category": "testing", "keywords": ["fixture"], "color": "green",
            "targets": targets, "agentPrefix": prefix,
        }
        (tdir / "team.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8", newline="\n")
        adir = tdir / "agents" / agent
        adir.mkdir()
        shutil.copy(root / DEV / "agents/dev-coder/prompt.md", adir / "prompt.md")
        ameta = json.loads((root / DEV / "agents/dev-coder/agent.json").read_text(encoding="utf-8"))
        ameta["name"] = agent
        if caps is not None:
            ameta["capabilities"] = caps
        (adir / "agent.json").write_text(json.dumps(ameta, indent=2) + "\n", encoding="utf-8", newline="\n")
        sdir = tdir / "skills" / name
        (sdir / "skill.json").write_text(json.dumps({
            "name": name,
            "description": "Calls the fixture team to run its helper agent. Use when the tests need a second team.",
            "agents": [agent],
        }, indent=2) + "\n", encoding="utf-8", newline="\n")
        (sdir / "instructions.md").write_text(
            "# Fixture\n\nRun {{agent:%s}} on the task.\n" % agent, encoding="utf-8", newline="\n")
        self.edit_json("catalog.json", lambda d: d["teams"].append(name))
        if readme:
            self.edit_text("README.md", lambda t: t + "\n`%s` `%s`\n" % (name, agent))
        return tdir

    def build_write(self):
        self.assertEqual(build.main(["--root", str(self.root)]), 0)

    def validate(self):
        return build.validate(self.root)

    def outputs(self):
        catalog, f = build.load_sources(self.root)
        self.assertIsNotNone(catalog, f)
        return build.render_outputs(catalog)


class Part1Test(TeamFixture):
    def test_t1_clean_repo_and_generated_set(self):
        self.assertEqual(errors_of(self.validate()), [])
        want = {
            ".claude-plugin/marketplace.json", ".agents/plugins/marketplace.json",
            "dist/claude-code/gaisser-agents/.claude-plugin/plugin.json",
            "dist/claude-code/gaisser-agents/skills/dev-team/SKILL.md",
            "dist/codex/gaisser-agents/skills/dev-team/SKILL.md",
            "dist/codex-plugin/gaisser-agents/plugin.json",
            "dist/codex-plugin/gaisser-agents/skills/dev-team/SKILL.md",
        }
        for a in AGENTS:
            want.add("dist/claude-code/gaisser-agents/agents/%s.md" % a)
            want.add("dist/codex/gaisser-agents/agents/%s.toml" % a)
        self.assertEqual(len(want), 13)
        self.assertEqual(set(self.outputs()), want)

    def test_t2_marketplaces_and_renames(self):
        out = self.outputs()
        mp = json.loads(out[".claude-plugin/marketplace.json"])
        self.assertEqual(list(mp), ["name", "description", "owner", "plugins", "renames"])
        want = {"dev-pipeline": "dev-team", "dev-team": "gaisser-agents"}
        self.assertEqual(mp["renames"], want)
        self.assertNotIn("renames", json.loads(out[".agents/plugins/marketplace.json"]))
        disk = json.loads(read(self.root, ".claude-plugin/marketplace.json"))
        self.assertEqual(disk["renames"], want)
        self.assertEqual([p["name"] for p in mp["plugins"]], ["gaisser-agents"])
        self.assertEqual(mp["plugins"][0]["source"], "./dist/claude-code/gaisser-agents")

    def test_t3_architect_prompt_markers_and_length(self):
        text = read(self.root, DEV + "/agents/dev-architect/prompt.md")
        self.assertIn("<!-- dev-team plan -->", text)
        self.assertIn("<!-- dev-pipeline plan -->", text)
        n = len(text.rstrip("\n").split("\n"))
        self.assertTrue(25 <= n <= 80, n)

    def test_t4_rendered_claude_skill(self):
        text = self.outputs()["dist/claude-code/gaisser-agents/skills/dev-team/SKILL.md"]
        self.assertIn("\nname: dev-team\n", text)
        for needle in ("at most 2", "Review gate", "single-session",
                       "<!-- dev-team plan -->", "<!-- dev-pipeline plan -->",
                       "## Handoff template", "## Project memory"):
            self.assertIn(needle, text, needle)
        m = re.search(r"## Final report\n(.*?)(\n## |\Z)", text, re.S)
        self.assertIsNotNone(m)
        items = re.findall(r"^\d+\. ", m.group(1), re.M)
        self.assertEqual(len(items), 5, m.group(1))

    def test_t5_legacy_folder(self):
        (self.root / "agents/x").mkdir(parents=True)
        (self.root / "agents/x/agent.json").write_text("{}\n")
        self.assertTrue(has_error(self.validate(), "legacy folder", "agents/"))

    def test_t5b_legacy_skills_folder(self):
        (self.root / "skills").mkdir()
        self.assertTrue(has_error(self.validate(), "legacy folder", "skills/"))

    def test_t6_missing_team_folder(self):
        self.edit_json("catalog.json", lambda d: d["teams"].append("ghost-team"))
        self.assertTrue(has_error(self.validate(), "has no folder under teams/"))

    def test_t7_team_name_must_end_with_team(self):
        self.add_team("devteam", ["claude-code"])
        self.assertTrue(has_error(self.validate(), "end with '-team'"))

    def test_t8_entry_skill_missing(self):
        self.add_team("x-team", ["claude-code"])
        shutil.move(str(self.root / "teams/x-team/skills/x-team"),
                    str(self.root / "teams/x-team/skills/other"))
        self.assertTrue(has_error(self.validate(), "has no entry skill"))

    def test_t9_no_agents(self):
        _rmtree(self.root / DEV / "agents")
        self.assertTrue(has_error(self.validate(), "needs at least one agent"))

    def test_t10_cross_team_skill_agent(self):
        self.add_team("x-team", ["claude-code"])
        self.edit_json("teams/x-team/skills/x-team/skill.json",
                       lambda d: d.update(agents=["helper", "dev-architect"]))
        self.assertTrue(has_error(self.validate(), "does not belong to the same team"))

    def test_t11_duplicate_skill(self):
        self.add_team("x-team", ["claude-code"])
        shutil.copytree(self.root / DEV / "skills/dev-team", self.root / "teams/x-team/skills/dev-team")
        self.assertTrue(has_error(self.validate(), "skill 'dev-team' is defined by more than one team"))

    def test_t12_unexpected_files(self):
        (self.root / DEV / "fonts").mkdir()
        (self.root / DEV / "fonts/inter.ttf").write_bytes(b"x")
        (self.root / "teams/notes.txt").write_text("x\n")
        f = self.validate()
        self.assertTrue(has_error(f, "unexpected file", "teams/dev-team/fonts/inter.ttf"))
        self.assertTrue(has_error(f, "unexpected file", "teams/notes.txt"))

    def test_t13_agent_prefix(self):
        self.add_team("x-team", ["claude-code"], agent="helper", prefix="x-")
        self.assertTrue(has_error(self.validate(), "must start with the team's agentPrefix"))

    def test_t13b_bad_prefix_shape(self):
        self.add_team("x-team", ["claude-code"], agent="x-helper", prefix="x")
        self.assertTrue(has_error(self.validate(), "agentPrefix must be kebab-case and end with '-'"))

    def test_t14_renames(self):
        self.edit_json("catalog.json", lambda d: d["renames"].update({"dev-pipeline": "ghost"}))
        self.assertTrue(has_error(self.validate(), "chain does not resolve"))
        self.edit_json("catalog.json", lambda d: d.update(renames={"gaisser-agents": "dev-team"}))
        self.assertTrue(has_error(self.validate(), "is a current plugin"))
        self.edit_json("catalog.json", lambda d: d.update(renames={"a-x": "b-x", "b-x": "a-x"}))
        self.assertTrue(has_error(self.validate(), "cycle"))

    def test_t14b_renames_other_shapes(self):
        self.edit_json("catalog.json", lambda d: d.update(renames=[]))
        self.assertTrue(has_error(self.validate(), "'renames' must be an object"))
        self.edit_json("catalog.json", lambda d: d.update(renames={"Bad Name": "dev-team"}))
        self.assertTrue(has_error(self.validate(), "is not a valid plugin name"))
        self.edit_json("catalog.json", lambda d: d.update(renames={"old-x": 5}))
        self.assertTrue(has_error(self.validate(), "must be a plugin name or null"))
        self.edit_json("catalog.json", lambda d: d.update(
            renames={"old-x": None, "dev-pipeline": "dev-team", "dev-team": "gaisser-agents"}))
        self.assertEqual(errors_of(self.validate()), [])
        mp = json.loads(self.outputs()[".claude-plugin/marketplace.json"])
        self.assertIsNone(mp["renames"]["old-x"])

    def test_t14c_empty_renames_omitted(self):
        self.edit_json("catalog.json", lambda d: d.update(renames={}))
        mp = json.loads(self.outputs()[".claude-plugin/marketplace.json"])
        self.assertNotIn("renames", mp)
        self.edit_json("catalog.json", lambda d: d.pop("renames"))
        mp = json.loads(self.outputs()[".claude-plugin/marketplace.json"])
        self.assertNotIn("renames", mp)

    def test_t15_targets(self):
        for bad in (["cursor"], [], ["codex", "codex"], "codex"):
            self.edit_json(DEV + "/team.json", lambda d, b=bad: d.update(targets=b))
            self.assertTrue(has_error(self.validate(), "targets must be a non-empty list"), bad)

    def test_t16_claude_only_team(self):
        self.add_team("x-team", ["claude-code"])
        out = self.outputs()
        self.assertIn("dist/claude-code/gaisser-agents/agents/x-helper.md", out)
        self.assertIn("dist/claude-code/gaisser-agents/skills/x-team/SKILL.md", out)
        self.assertFalse([p for p in out if "x-helper" in p and not p.startswith("dist/claude-code/")])
        self.assertFalse([p for p in out if "/x-team/" in p and not p.startswith("dist/claude-code/")])
        cmp_ = json.loads(out[".claude-plugin/marketplace.json"])
        self.assertEqual([p["name"] for p in cmp_["plugins"]], ["gaisser-agents"])
        xmp = json.loads(out[".agents/plugins/marketplace.json"])
        self.assertEqual([p["name"] for p in xmp["plugins"]], ["gaisser-agents"])
        self.assertEqual(errors_of(self.validate()), [])

    def test_t16b_codex_only_team(self):
        self.add_team("x-team", ["codex"])
        out = self.outputs()
        self.assertFalse([p for p in out if "x-helper" in p and p.startswith("dist/claude-code/")])
        self.assertFalse([p for p in out if "/x-team/" in p and p.startswith("dist/claude-code/")])
        self.assertIn("dist/codex/gaisser-agents/agents/x-helper.toml", out)
        self.assertIn("dist/codex/gaisser-agents/skills/x-team/SKILL.md", out)
        self.assertIn("dist/codex-plugin/gaisser-agents/skills/x-team/SKILL.md", out)
        self.assertFalse([p for p in out if "x-helper" in p and p.startswith("dist/codex-plugin/")])

    def test_t16c_targets_filter_two_teams_one_manifest_per_tool(self):
        self.add_team("x-team", ["claude-code"])
        self.add_team("y-team", ["codex"])
        out = self.outputs()
        for path in ("dist/claude-code/gaisser-agents/agents/x-helper.md",
                     "dist/codex/gaisser-agents/agents/y-helper.toml",
                     "dist/codex-plugin/gaisser-agents/skills/y-team/SKILL.md"):
            self.assertIn(path, out)
        self.assertNotIn("dist/codex/gaisser-agents/agents/x-helper.toml", out)
        self.assertNotIn("dist/claude-code/gaisser-agents/agents/y-helper.md", out)
        self.assertNotIn("dist/codex-plugin/gaisser-agents/skills/x-team/SKILL.md", out)
        manifests = [p for p in out if p.endswith("plugin.json")]
        self.assertEqual(sorted(manifests), [
            "dist/claude-code/gaisser-agents/.claude-plugin/plugin.json",
            "dist/codex-plugin/gaisser-agents/plugin.json"])
        self.assertEqual(errors_of(self.validate()), [])

    def test_t16d_two_teams_both_tools_share_one_plugin(self):
        self.add_team("x-team", ["claude-code", "codex"])
        out = self.outputs()
        manifests = [p for p in out if p.endswith("plugin.json")]
        self.assertEqual(len(manifests), 2, manifests)
        for path in ("dist/claude-code/gaisser-agents/agents/dev-coder.md",
                     "dist/claude-code/gaisser-agents/agents/x-helper.md",
                     "dist/claude-code/gaisser-agents/skills/dev-team/SKILL.md",
                     "dist/claude-code/gaisser-agents/skills/x-team/SKILL.md",
                     "dist/codex/gaisser-agents/agents/dev-coder.toml",
                     "dist/codex/gaisser-agents/agents/x-helper.toml",
                     "dist/codex-plugin/gaisser-agents/skills/dev-team/SKILL.md",
                     "dist/codex-plugin/gaisser-agents/skills/x-team/SKILL.md"):
            self.assertIn(path, out)
        self.assertEqual(len(json.loads(out[".claude-plugin/marketplace.json"])["plugins"]), 1)
        self.assertEqual(len(json.loads(out[".agents/plugins/marketplace.json"])["plugins"]), 1)
        self.assertFalse([p for p in out if "/x-team/" in p and "/skills/" not in p])

    def test_t16e_no_team_targets_a_tool_warns(self):
        self.edit_json(DEV + "/team.json", lambda d: d.update(targets=["claude-code"]))
        f = self.validate()
        self.assertTrue(has_warn(f, "no team targets 'codex'"), f)
        self.assertEqual(errors_of(f), [])
        out = self.outputs()
        self.assertFalse([p for p in out if p.startswith("dist/codex")])
        self.assertEqual(json.loads(out[".agents/plugins/marketplace.json"])["plugins"], [])

    def test_t16f_cross_team_agent_collision(self):
        self.add_team("x-team", ["claude-code"], agent="dev-architect", prefix="x-")
        self.assertTrue(has_error(self.validate(),
                                  "agent 'dev-architect' is defined by more than one team",
                                  "catalog.json"))

    def test_t16g_missing_agent_prefix(self):
        self.edit_json(DEV + "/team.json", lambda d: d.pop("agentPrefix"))
        self.assertTrue(has_error(self.validate(), "missing key 'agentPrefix'", DEV + "/team.json"))

    def test_t16h_duplicate_prefix_across_teams(self):
        self.add_team("x-team", ["claude-code"], agent="dev-helper", prefix="dev-")
        self.assertTrue(has_error(self.validate(), "agentPrefix 'dev-' is used by more than one team",
                                  "catalog.json"))

    def test_t16i_team_json_with_version_is_unknown_key(self):
        self.edit_json(DEV + "/team.json", lambda d: d.update(version="2.0.0"))
        self.assertTrue(has_error(self.validate(), "unknown key 'version'", DEV + "/team.json"))

    def test_t16j_renames_chain_must_end_at_plugin_name(self):
        self.edit_json("catalog.json", lambda d: d.update(renames={"dev-pipeline": "dev-team"}))
        self.assertTrue(has_error(self.validate(), "chain does not resolve", "catalog.json"))
        self.edit_json("catalog.json", lambda d: d.update(renames={"dev-team": "gaisser-agents"}))
        self.assertEqual(errors_of(self.validate()), [])

    def test_t16k_plugin_block_validation(self):
        self.edit_json("catalog.json", lambda d: d["plugin"].update(version="3.0"))
        self.assertTrue(has_error(self.validate(), "plugin version must be semver", "catalog.json"))
        self.edit_json("catalog.json", lambda d: d["plugin"].update(version="3.0.0", name="my-claude-x"))
        self.assertTrue(has_error(self.validate(), "must not contain 'claude'", "catalog.json"))
        self.edit_json("catalog.json", lambda d: d.pop("plugin"))
        self.assertTrue(has_error(self.validate(), "missing key 'plugin'", "catalog.json"))

    def test_t17_unreferenced_agent_warns(self):
        self.edit_json(DEV + "/skills/dev-team/skill.json",
                       lambda d: d.update(agents=["dev-architect", "dev-coder"]))
        self.edit_text(DEV + "/skills/dev-team/instructions.md",
                       lambda t: t.replace("{{agent:dev-tester}}", "dev-tester"))
        f = self.validate()
        self.assertTrue(has_warn(f, "is not referenced by the entry skill"), f)
        self.assertEqual(errors_of(f), [])

    def test_t18_broken_source_does_not_crash(self):
        (self.root / DEV / "agents/dev-coder/agent.json").unlink()
        self.assertEqual(build.main(["--root", str(self.root), "--check"]), 1)
        self.assertEqual(build.main(["--root", str(self.root)]), 1)

    def test_t18b_other_broken_sources_do_not_crash(self):
        cases = [("catalog.json", "{not json"), ("catalog.json", "[]"),
                 (DEV + "/team.json", "[]"), (DEV + "/team.json", "{}"),
                 (DEV + "/agents/dev-coder/agent.json", "[]"),
                 (DEV + "/skills/dev-team/skill.json", "[]")]
        for i, (rel, content) in enumerate(cases):
            root = Path(self._tmp) / ("c%d" % i)
            copy_repo(root)
            (root / rel).write_text(content, encoding="utf-8")
            self.assertEqual(build.main(["--root", str(root), "--check"]), 1, (rel, content))

    def test_t18d_unhashable_values_do_not_crash(self):
        """Unhashable JSON values are reported as errors, not raised as TypeError."""
        cases = [
            (DEV + "/agents/dev-coder/agent.json", {"capabilities": [["read"]]}),
            (DEV + "/agents/dev-coder/agent.json", {"model": []}),
            (DEV + "/agents/dev-coder/agent.json", {"effort": []}),
            (DEV + "/team.json", {"targets": [["codex"]]}),
            (DEV + "/team.json", {"color": []}),
        ]
        for i, (rel, upd) in enumerate(cases):
            root = Path(self._tmp) / ("u%d" % i)
            copy_repo(root)
            data = json.loads((root / rel).read_text(encoding="utf-8"))
            data.update(upd)
            (root / rel).write_text(json.dumps(data), encoding="utf-8")
            self.assertEqual(build.main(["--root", str(root), "--check"]), 1, (rel, upd))

    def test_t18c_teams_folder_missing(self):
        _rmtree(self.root / "teams")
        self.assertEqual(build.main(["--root", str(self.root), "--check"]), 1)

    def test_t19_version_bump_base_without_plugin_key_is_skipped(self):
        def git(*a):
            r = subprocess.run(["git", *GIT_ID, *a], cwd=str(self.root), capture_output=True,
                               text=True, encoding="utf-8")
            self.assertEqual(r.returncode, 0, r.stderr)
        self.edit_json("catalog.json", lambda d: d.pop("plugin"))
        git("init", "-q", "-b", "main")
        git("add", "-A")
        git("commit", "-q", "-m", "base")
        self.edit_json("catalog.json", lambda d: d.update(plugin=json.loads(
            read(REPO, "catalog.json"))["plugin"]))
        self.add_team("x-team", ["claude-code", "codex"])
        self.build_write()
        git("add", "-A")
        git("commit", "-q", "-m", "new team")
        self.assertEqual(build.check_version_bumps(self.root, "HEAD~1"), [])

    def test_t20_installers_hints(self):
        if os.path.isfile(BASH):
            base = Path(self._tmp) / "b sh"
            base.mkdir()
            r = subprocess.run([BASH, sh_path(REPO / "install.sh"), "--target", "all",
                                "--plugin", "gaisser-agents", "--base", sh_path(base)],
                               capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
            self.assertIn("/dev-team", r.stdout)
            self.assertIn("$dev-team", r.stdout)
            self.assertIn("'dev-architect', not 'gaisser-agents:dev-architect'", r.stdout)
            self.assertNotIn("pipeline", r.stdout)
        if sys.platform == "win32" and shutil.which(POWERSHELL):
            base = Path(self._tmp) / "b ps"
            base.mkdir()
            r = subprocess.run([POWERSHELL, "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
                                str(REPO / "install.ps1"), "-Target", "all", "-Plugin", "gaisser-agents",
                                "-Base", str(base)],
                               capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
            self.assertIn("/dev-team", r.stdout)
            self.assertIn("$dev-team", r.stdout)
            self.assertIn("'dev-architect', not 'gaisser-agents:dev-architect'", r.stdout)
            self.assertNotIn("pipeline", r.stdout)

    def test_t20b_installers_and_ci_have_no_legacy_names(self):
        for rel in (".github/workflows/ci.yml", "install.sh", "install.ps1"):
            t = read(REPO, rel)
            self.assertNotIn("skills/pipeline", t, rel)
            self.assertNotIn("dev-pipeline", t, rel)


class Part1ContentTest(unittest.TestCase):
    """T30 to T34: the prompts, skill, README and seed memory agree."""

    @classmethod
    def setUpClass(cls):
        catalog, _ = build.load_sources(REPO)
        cls.outputs = build.render_outputs(catalog)
        cls.skill_src = read(REPO, DEV + "/skills/dev-team/instructions.md")
        cls.skill = cls.outputs["dist/claude-code/gaisser-agents/skills/dev-team/SKILL.md"]
        cls.prompts = {a.split("-", 1)[1]: read(REPO, DEV + "/agents/%s/prompt.md" % a)
                       for a in AGENTS}

    FIELDS = ["Goal", "Context", "Constraints", "Files to touch", "Out of scope", "Acceptance criteria"]

    def test_t30_handoff_contract(self):
        m = re.search(r"## Handoff template\n(.*)", self.skill_src, re.S)
        self.assertIsNotNone(m)
        block = re.search(r"```[a-z]*\n(.*?)\n```", m.group(1), re.S)
        self.assertIsNotNone(block, "no fenced block after '## Handoff template'")
        body = block.group(1)
        self.assertTrue(body.startswith("## Handoff"), body[:40])
        heads = re.findall(r"^### (.+)$", body, re.M)
        self.assertEqual(heads, self.FIELDS)
        self.assertIn(", ".join(self.FIELDS), self.prompts["architect"])
        self.assertIn("Files to touch", self.prompts["coder"])
        self.assertIn("Out of scope", self.prompts["coder"])
        self.assertIn("acceptance criteria", self.prompts["tester"])

    MEMORY = ["docs/decisions/", "docs/lessons-learned.md", "- Date: YYYY-MM-DD",
              "- Status: accepted", "- Decision: ...", "- Reason: ...",
              "superseded by NNNN", "Source: <what happened>"]

    def test_t31_memory_contract(self):
        for needle in self.MEMORY:
            self.assertIn(needle, self.skill_src, "skill: " + needle)
            self.assertIn(needle, self.prompts["architect"], "architect: " + needle)

    def test_t32_routing_and_reports(self):
        for needle in ("Verdict: fail", "`implementation`", "`design`", "at most 2 fix cycles",
                       "apply the review gate to the revised plan", "**Record.**"):
            self.assertIn(needle, self.skill, needle)
        for needle in ("**Verdict:**", "**Criteria:**", "**Extra cases:**",
                       "When in doubt, choose `design`"):
            self.assertIn(needle, self.prompts["tester"], needle)
        self.assertIn("## Revisions", self.prompts["architect"])
        self.assertIn("## Revisions", self.prompts["coder"])
        for a in AGENTS:
            meta = json.loads(read(REPO, DEV + "/agents/%s/agent.json" % a))
            md = read(REPO, "dist/claude-code/gaisser-agents/agents/%s.md" % a)
            self.assertIn("description: " + build.dq(meta["description"]) + "\n", md)

    def test_t33_readme(self):
        t = read(REPO, "README.md")
        for needle in ("## Call a team", "## Migrating from dev-pipeline", "Files to touch",
                       "docs/decisions/", "at most 2 fix cycles"):
            self.assertIn(needle, t, needle)

    def test_t34_seed_memory(self):
        files = sorted((REPO / "docs/decisions").glob("*.md"))
        self.assertTrue(files)
        for i, p in enumerate(files, 1):
            self.assertRegex(p.name, r"^\d{4}-[a-z0-9-]+\.md$")
            self.assertEqual(int(p.name[:4]), i, "numbers must run from 0001 with no gaps")
            text = read(REPO, "docs/decisions/" + p.name)
            self.assertTrue(text.split("\n")[0].startswith("# %04d. " % i))
            self.assertRegex(text, r"(?m)^- Date: \d{4}-\d{2}-\d{2}$")
            self.assertRegex(text, r"(?m)^- Status: (accepted|superseded by \d{4})$")
            self.assertRegex(text, r"(?m)^- Decision: .+")
            self.assertRegex(text, r"(?m)^- Reason: .+")
        ll = read(REPO, "docs/lessons-learned.md")
        self.assertTrue(ll.startswith("# Lessons learned"))
        bullets = [x for x in ll.split("\n") if x.startswith("- ")]
        self.assertTrue(bullets)
        for b in bullets:
            self.assertRegex(b, r"^- \d{4}-\d{2}-\d{2}: .+ Source: .+\.$")


class Part2Test(TeamFixture):
    def test_t21_inherit(self):
        self.edit_json(DEV + "/agents/dev-coder/agent.json", lambda d: d.update(capabilities="inherit"))
        out = self.outputs()
        md = out["dist/claude-code/gaisser-agents/agents/dev-coder.md"]
        self.assertNotIn("\ntools:", md)
        self.assertIn("\ndisallowedTools: Agent\n", md)
        toml = out["dist/codex/gaisser-agents/agents/dev-coder.toml"]
        self.assertNotIn("sandbox_mode", toml)
        tomllib.loads(toml)
        self.assertEqual(errors_of(self.validate()), [])
        self.edit_json(DEV + "/agents/dev-coder/agent.json", lambda d: d.update(capabilities="all"))
        self.assertTrue(has_error(self.validate(), 'capabilities must be "inherit"'))

    def test_t21b_inherit_web_rule_warns(self):
        self.edit_json(DEV + "/agents/dev-coder/agent.json", lambda d: d.update(capabilities="inherit"))
        self.assertTrue(has_warn(self.validate(), "untrusted web content rule"))

    def test_t22_effort(self):
        self.edit_json(DEV + "/agents/dev-coder/agent.json", lambda d: d.update(model="fast", effort="low"))
        self.assertTrue(has_error(self.validate(), "must not set effort"))
        self.edit_json(DEV + "/agents/dev-coder/agent.json",
                       lambda d: (d.update(model="fast"), d.pop("effort", None)))
        self.assertEqual(errors_of(self.validate()), [])
        out = self.outputs()
        self.assertNotIn("\neffort:", out["dist/claude-code/gaisser-agents/agents/dev-coder.md"])
        self.assertNotIn("model_reasoning_effort", out["dist/codex/gaisser-agents/agents/dev-coder.toml"])

    def test_t23_codex_names(self):
        self.add_team("x-team", ["claude-code", "codex"], agent="x-helper", prefix="x-")
        out = self.outputs()
        toml = out["dist/codex/gaisser-agents/agents/x-helper.toml"]
        self.assertEqual(tomllib.loads(toml)["name"], "x_helper")
        cskill = out["dist/codex/gaisser-agents/skills/x-team/SKILL.md"]
        self.assertIn("`x_helper`", cskill)
        self.assertNotIn("gaisser-agents:x-helper", cskill)
        self.assertIn("`gaisser-agents:x-helper`", out["dist/claude-code/gaisser-agents/skills/x-team/SKILL.md"])
        self.assertIn("\nname: x-helper\n", out["dist/claude-code/gaisser-agents/agents/x-helper.md"])
        self.assertEqual(errors_of(self.validate()), [])

    def test_t24_reserved_after_mapping(self):
        self.add_team("x-team", ["codex"], agent="max-threads", prefix="max-")
        self.assertTrue(has_error(self.validate(), "reserved Codex name"))

    def sf(self, name="x-team"):
        return self.root / "teams" / name / "skills" / name

    def skill_file(self, sub, fname, data):
        d = self.sf() / sub
        d.mkdir(exist_ok=True)
        p = d / fname
        p.write_bytes(data if isinstance(data, bytes) else data.encode("utf-8"))
        return p

    def test_t25_skill_files_copied_for_each_target(self):
        self.add_team("x-team", ["claude-code", "codex"])
        self.skill_file("assets", "brand-profile.md", "# Brand\n\nvoice\n")
        self.skill_file("references", "notes.json", '{"a": 1}\n')
        self.assertEqual(errors_of(self.validate()), [])
        out = self.outputs()
        for base in ("dist/claude-code/gaisser-agents", "dist/codex/gaisser-agents", "dist/codex-plugin/gaisser-agents"):
            self.assertEqual(out[base + "/skills/x-team/assets/brand-profile.md"], "# Brand\n\nvoice\n")
            self.assertIn(base + "/skills/x-team/references/notes.json", out)

    def test_t25b_skill_file_errors(self):
        self.add_team("x-team", ["claude-code"])
        cases = [
            ("assets", "font.ttf", b"x", "unexpected file"),
            ("assets", "My File.md", b"x", "unexpected file"),
            ("references", "My File.md", b"x", "unexpected file"),
            ("other", "x.md", b"x", "unexpected file"),
            ("assets", "bom.md", b"\xef\xbb\xbfhello\n", "BOM"),
            ("assets", "big.md", b"a" * 70000, "larger than 64 KiB"),
            ("assets", "emoji.md", "hi \U0001F600\n".encode("utf-8"), "emoji are not allowed"),
            ("assets", "nul.md", b"a\x00b\n", "NUL"),
            ("assets", "bad-utf8.md", b"\xff\xfe\x00", None),
        ]
        for sub, fname, data, msg in cases:
            p = self.skill_file(sub, fname, data)
            f = self.validate()
            if msg is None:
                self.assertTrue(errors_of(f), fname)
            else:
                self.assertTrue(has_error(f, msg), (fname, [x.message for x in errors_of(f)]))
            p.unlink()
        _rmtree(self.sf() / "other")
        self.assertEqual(errors_of(self.validate()), [])
        d = self.sf() / "assets" / "sub"
        d.mkdir()
        (d / "x.md").write_text("x\n")
        self.assertTrue(has_error(self.validate(), "unexpected file"))

    def test_t25c_skill_files_never_crash_main(self):
        self.add_team("x-team", ["claude-code"])
        self.skill_file("assets", "nul.md", b"a\x00b\n")
        self.skill_file("assets", "bad-utf8.md", b"\xff\xfe\x00")
        self.skill_file("assets", "big.md", b"a" * 70000)
        self.assertEqual(build.main(["--root", str(self.root), "--check"]), 1)

    def test_t25d_skill_file_crlf_normalized(self):
        self.add_team("x-team", ["claude-code"])
        self.skill_file("assets", "a.md", b"one\r\ntwo\r\n")
        out = self.outputs()
        self.assertEqual(out["dist/claude-code/gaisser-agents/skills/x-team/assets/a.md"], "one\ntwo\n")

    def test_t25e_skill_files_are_checked_and_written(self):
        self.add_team("x-team", ["claude-code", "codex"])
        self.skill_file("assets", "a.md", "alpha\n")
        self.build_write()
        p = self.root / "dist/codex/gaisser-agents/skills/x-team/assets/a.md"
        self.assertEqual(p.read_text(encoding="utf-8"), "alpha\n")
        self.assertEqual(build.main(["--root", str(self.root), "--check"]), 0)
        p.write_text("tampered\n")
        self.assertEqual(build.main(["--root", str(self.root), "--check"]), 1)
        (self.sf() / "assets" / "a.md").unlink()
        self.build_write()
        self.assertFalse(p.exists())

    def test_t26_model_invocable_warn(self):
        self.add_team("x-team", ["claude-code"])
        self.edit_json("teams/x-team/skills/x-team/skill.json", lambda d: d.update(modelInvocable=False))
        self.assertFalse(has_warn(self.validate(), "manual-only invocation"))
        self.assertIn("disable-model-invocation: true",
                      self.outputs()["dist/claude-code/gaisser-agents/skills/x-team/SKILL.md"])
        self.edit_json("teams/x-team/team.json", lambda d: d.update(targets=["claude-code", "codex"]))
        self.assertTrue(has_warn(self.validate(), "manual-only invocation"))

    def test_t27_no_output_change(self):
        r = subprocess.run([sys.executable, str(REPO / "scripts/build.py"), "--check"],
                           capture_output=True, text=True, encoding="utf-8", cwd=str(REPO))
        self.assertEqual(r.returncode, 0, r.stdout)
        self.assertTrue(r.stdout.strip().endswith("0 error(s), 0 warning(s)"), r.stdout)

    def test_build_is_idempotent(self):
        self.add_team("x-team", ["claude-code", "codex"])
        self.skill_file("assets", "a.md", "alpha\n")
        self.build_write()
        snap1 = {p.relative_to(self.root).as_posix(): p.read_bytes()
                 for p in (self.root / "dist").rglob("*") if p.is_file()}
        self.build_write()
        snap2 = {p.relative_to(self.root).as_posix(): p.read_bytes()
                 for p in (self.root / "dist").rglob("*") if p.is_file()}
        self.assertEqual(snap1, snap2)
        self.assertEqual(build.main(["--root", str(self.root), "--check"]), 0)
        catalog, _ = build.load_sources(self.root)
        written, removed = build.write_outputs(self.root, build.render_outputs(catalog))
        self.assertEqual(removed, 0)

    def test_every_dist_file_comes_from_the_build(self):
        catalog, _ = build.load_sources(REPO)
        outputs = build.render_outputs(catalog)
        on_disk = set(build._generated_files_on_disk(REPO))
        gen = set(outputs) - {".claude-plugin/marketplace.json", ".agents/plugins/marketplace.json"}
        self.assertEqual(on_disk, gen)


class Part2InstallBase:
    """T28 and T29 against a temp copy of the repository (never the real home)."""

    def setUp(self):
        super().setUp()
        self.inst = Path(self._tmp) / "inst base"
        self.inst.mkdir()

    def prepare(self, targets):
        self.add_team("x-team", targets)
        d = self.root / "teams/x-team/skills/x-team/assets"
        d.mkdir()
        (d / "a.md").write_text("alpha\n", encoding="utf-8", newline="\n")
        self.build_write()

    def test_t28_folder_comparison(self):
        self.prepare(["claude-code", "codex"])
        code, out, err = self.run_install("claude", "--plugin", "gaisser-agents")
        self.assertEqual(code, 0, out + err)
        inst = self.inst / ".claude/skills/x-team/assets/a.md"
        self.assertTrue(inst.is_file(), out)
        code, out, err = self.run_install("claude", "--plugin", "gaisser-agents")
        self.assertIn("[unchanged]", out)
        self.assertNotIn("[skipped]", out)
        orig = inst.read_bytes()
        inst.write_bytes(orig + b"local\n")
        code, out, err = self.run_install("claude", "--plugin", "gaisser-agents")
        self.assertEqual(code, 0, out + err)
        self.assertIn("[skipped]", out)
        self.assertEqual(inst.read_bytes(), orig + b"local\n")
        inst.write_bytes(orig)
        code, out, err = self.run_install("claude", "--plugin", "gaisser-agents")
        self.assertEqual(code, 0, out + err)
        self.assertEqual(out.count("[unchanged]"), 6, out)
        self.assertNotIn("[skipped]", out)

    def test_t28b_extra_file_in_installed_skill_is_skipped(self):
        self.prepare(["claude-code"])
        self.run_install("claude", "--plugin", "gaisser-agents")
        (self.inst / ".claude/skills/x-team/assets/extra.md").write_text("e\n")
        code, out, err = self.run_install("claude", "--plugin", "gaisser-agents")
        self.assertEqual(code, 0, out + err)
        self.assertIn("[skipped]", out)

    def test_t29_targets_filter_in_installers(self):
        self.prepare(["claude-code"])
        code, out, err = self.run_install("all", "--all")
        self.assertEqual(code, 0, out + err)
        self.assertNotIn("n/a", out)
        self.assertTrue((self.inst / ".claude/skills/dev-team/SKILL.md").is_file())
        self.assertTrue((self.inst / ".claude/skills/x-team/SKILL.md").is_file())
        self.assertTrue((self.inst / ".claude/agents/x-helper.md").is_file())
        self.assertFalse((self.inst / ".agents/skills/x-team").exists())
        self.assertFalse((self.inst / ".codex/agents/x-helper.toml").exists())
        self.assertTrue((self.inst / ".codex/agents/dev-coder.toml").is_file())


@unittest.skipUnless(os.path.isfile(BASH), "Git Bash not found")
class Part2InstallShTest(Part2InstallBase, TeamFixture):
    def run_install(self, target, *args):
        a = ["--target", target, "--base", sh_path(self.inst)] + list(args)
        r = subprocess.run([BASH, sh_path(self.root / "install.sh")] + a, capture_output=True,
                           text=True, encoding="utf-8", cwd=str(self.root))
        return r.returncode, r.stdout, r.stderr


@unittest.skipUnless(sys.platform == "win32" and shutil.which(POWERSHELL), "Windows PowerShell not found")
class Part2InstallPs1Test(Part2InstallBase, TeamFixture):
    def run_install(self, target, *args):
        a = ["-Target", target, "-Base", str(self.inst)]
        for x in args:
            a.append({"--plugin": "-Plugin", "--all": "-All"}.get(x, x))
        r = subprocess.run([POWERSHELL, "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
                            str(self.root / "install.ps1")] + a, capture_output=True,
                           text=True, encoding="utf-8", cwd=str(self.root))
        return r.returncode, r.stdout, r.stderr


if __name__ == "__main__":
    unittest.main()
